export const copy = {
  en: {
    howItWorks: 'How KCMS works', signIn: 'Sign in', language: 'ភាសាខ្មែរ',
    eyebrow: 'Khmer-first comment moderation',
    heading: 'Moderate Khmer comments with context—not guesswork.',
    description: 'Find harmful comments and scams faster. KCMS helps your team prioritize what needs attention, while humans decide every moderation action.',
    requestAccess: 'Request access', seeHow: 'See how it works',
    pathwayLabel: 'How a comment reaches human review', incoming: 'Facebook Page comment',
    sampleComment: 'ចុចតំណនេះទទួលលុយ $500 ថ្ងៃនេះ!', pattern: 'Automatic detection',
    patternDetail: 'Pattern matching · v0.1', review: 'Needs human review',
    reviewDetail: 'Possible scam signal', human: 'Your team decides',
    humanDetail: 'Leave · Hide · Unhide · Correct label', noAutomatic: 'Automatic detection · Human-approved Page actions',
    facebook: 'Facebook comments', languageSupport: 'Khmer + Khmerlish', humanControlled: 'Human controlled',
    overviewEyebrow: 'Service overview',
    overviewHeading: 'See one Facebook comment move through KCMS.',
    overviewDescription: 'A comment is detected automatically, reviewed by a person, and hidden or restored on the connected Page. This prototype walkthrough will be replaced by a recording of the verified live flow.',
    overviewDemoCta: 'Open the client workspace',
    overviewLoopLabel: 'Prototype walkthrough',
    overviewPause: 'Pause animation',
    overviewPlay: 'Play animation',
    overviewVideoUnsupported: 'Your browser cannot play this overview video.',
    overviewTranscriptLabel: 'Service overview transcript',
    overviewChapters: [
      'Comment posted on Facebook',
      'Automatic detection',
      'Human review',
      'Hide confirmed on Facebook',
      'Unhide restores the comment',
    ],
    workflowEyebrow: 'Three clear handoffs',
    workflowHeading: 'From Facebook comment to human decision.',
    workflowDescription: 'KCMS keeps the first version simple: connect a Page, surface comments that need attention, and let your team decide the action. No Meta developer workflow for client staff.',
    workflowSteps: [
      {
        title: 'Connect the Page',
        body: 'A Client links the Facebook Page once. KCMS keeps connection health visible so the team knows whether comments are still arriving.',
        meta: 'Setup',
      },
      {
        title: 'Prioritize review',
        body: 'Versioned pattern matching flags Khmer, Khmer slang, Khmerlish, scams, and harmful phrases while preserving ordinary complaints.',
        meta: 'Pattern matching v0.1',
      },
      {
        title: 'Decide with context',
        body: 'A trusted Client leaves, hides, unhides, or corrects the label. The action and the label stay separate for later learning.',
        meta: 'Human controlled',
      },
    ],
    navHumanControl: 'Human control',
    setTitle: 'Settings', setLead: 'Your workspace and your account.',
    setWorkspace: 'Workspace', setWorkspaceName: 'Workspace name',
    setWorkspaceOwnerOnly: 'Only an owner can rename the workspace.',
    setYou: 'You', setYourName: 'Your display name',
    setNameNote: 'Shown on the actions you take from now on. Past actions keep the name you used at the time.',
    setSave: 'Save', setSaved: 'Saved', setSaving: 'Saving…',
    setPlan: 'Workspace type', setSandbox: 'Demo workspace', setConnected: 'Approved',
    setSignOut: 'Sign out of KCMS',
    errNameRequired: 'Please enter a name.',
    teamTitle: 'Team', teamLead: 'People who can moderate this workspace.',
    teamYou: 'You', teamOwner: 'Owner', teamMember: 'Member',
    teamInvite: 'Create invitation link',
    teamInviteRole: 'Joins as',
    teamLinkTitle: 'Share this link',
    teamLinkBody: 'It works once and expires in 7 days. We cannot show it again, so copy it now.',
    teamCopy: 'Copy link', teamCopied: 'Copied',
    teamOpenInvites: 'Open invitations', teamRevoke: 'Revoke',
    teamExpires: 'Expires', teamRemove: 'Remove', teamPending: 'Pending',
    teamLastOwner: 'A workspace must keep at least one owner. Make someone else an owner first.',
    teamLeave: 'Leave this workspace',
    teamLeaveConfirm: 'Leave this workspace? You will no longer see its comments, and only an owner can add you back.',
    teamLeaveYes: 'Leave workspace',
    teamLeaveError: 'You could not be removed from this workspace. Please try again.',
    teamOwnerOnly: 'Only an owner can invite or remove people.',
    joinTitle: 'Join', joinRole: 'You will join as',
    joinAccept: 'Join workspace', joinSignInFirst: 'Sign in to accept this invitation',
    joinInvalid: 'This invitation is invalid, expired, or already used.',
    joinDone: 'You have joined',
    adminTitle: 'Access requests', adminOps: 'Platform operations',
    adminPending: 'Pending', adminAll: 'All', adminEmpty: 'No requests right now.',
    adminApprove: 'Approve', adminDecline: 'Decline',
    adminReason: 'Reason for declining', adminReasonHint: 'The client sees this.',
    adminConfirmDecline: 'Confirm decline', adminCancel: 'Cancel',
    adminMonthly: 'comments/month', adminModerators: 'moderators',
    navAdmin: 'Administration',
    dashWorkspace: 'Client workspace',
    dashNavOverview: 'Overview',
    dashNavModerate: 'Moderate',
    dashNavPage: 'Management',
    dashNavTeam: 'Team',
    dashNavSettings: 'Settings',
    dashNavProfile: 'Profile',
    dashNavRules: 'Moderation rules',
    rulesTitle: 'Moderation rules',
    rulesLead: 'Words that always surface a comment for review, however it is spelled around them.',
    rulesAddTitle: 'Add a stop word',
    rulesAddLead: 'The word is appended to the workspace rule list and applies to comments collected from now on.',
    rulesWord: 'Word or phrase',
    rulesWordRequired: 'Please enter a word to add.',
    rulesWordHint: 'Khmer, Khmerlish or English. Matching ignores case and surrounding punctuation.',
    rulesSeverity: 'Severity',
    rulesNote: 'Note (optional)',
    rulesNoteHint: 'Why this word is on the list. Shown to reviewers, never to the public.',
    rulesAdd: 'Add word',
    rulesAdding: 'Adding…',
    rulesAdded: (word: string) => `Added “${word}” to the rule list.`,
    rulesDuplicate: 'That word is already on the list.',
    rulesEmpty: 'No stop words yet',
    rulesEmptyLead: 'Add the first word and every new comment containing it is surfaced for review.',
    rulesListTitle: 'Current stop words',
    rulesCount: (n: number) => `${n} word${n === 1 ? '' : 's'}`,
    rulesSearch: 'Search words',
    rulesNoMatch: 'No word matches that search.',
    rulesRemove: 'Remove',
    rulesRemoveFailed: 'That word could not be removed. Please try again.',
    rulesAddFailed: 'That word could not be saved. Please try again.',
    rulesUnavailable: 'Moderation rules are not available on this workspace yet.',
    rulesUnavailableLead: 'The rule list endpoint is not deployed. Words added here cannot be saved until it is.',
    connAddTitle: 'Add a Page',
    connAddLead: 'Choose a Page you administer. KCMS collects its comments for review.',
    connAdd: 'Add Page',
    connAdding: 'Opening…',
    connAddFeature1: 'Pages you administer are discovered automatically',
    connAddFeature2: 'Only comment moderation permissions are requested',
    connAddFeature3: 'A Page can be disconnected at any time',
    connMethodFacebook: 'Facebook Page',
    dashNotBuilt: 'Not in the prototype',
    proTitle: 'Profile',
    proLead: 'Your identity in this workspace, and how KCMS behaves for you.',
    proIdentity: 'Signed in as',
    proAccount: 'Account',
    proAccountLead: 'How you appear on every moderation action you take.',
    proDetails: 'Account details',
    proDetailsLead: 'Read-only facts about this account and the workspace it belongs to.',
    proRole: 'Workspace role',
    proWorkspace: 'Workspace',
    proUserId: 'User ID',
    proAccess: 'Access level',
    proAdmin: 'Platform administrator',
    proStandard: 'Workspace user',
    proPreferences: 'Preferences',
    proPreferencesLead: 'Applies to this browser only. Nothing is saved to the workspace.',
    proLanguage: 'Interface language',
    proLanguageHint: 'Switches every screen between English and Khmer.',
    proSession: 'Session',
    proSessionLead: 'Signing out ends this session on this device only.',
    proWorkspaceLink: 'Workspace settings',
    proWorkspaceLinkLead: 'Workspace name, plan and sample data live in Settings.',
    proOpenSettings: 'Open settings',
    setYouLead: 'Your display name and preferences moved to your profile.',
    setOpenProfile: 'Open profile',
    setGeneral: 'General',
    setGeneralLead: 'The name your team sees, and what kind of workspace this is.',
    setDangerZone: 'Data',
    setWorkspaceId: 'Workspace ID',
    setNavGeneral: 'General',
    setNavData: 'Data',
    setNavProfile: 'Profile',
    setNavRules: 'Rules',
    setRules: 'Moderation Rules',
    setRulesLead: 'Keywords for this workspace only. Other workspaces are unaffected by what you add here.',
    setRulesAdd: 'Add keyword',
    setRulesAddTitle: 'Add a keyword',
    setRulesAddLead: 'Applies to comments collected from now on, in this workspace only.',
    setRulesListTitle: 'Your keywords',
    setRulesListLead: 'On top of the Khmer patterns KCMS ships with, which always apply.',
    setRulesEmptyTitle: 'No keywords yet',
    setRulesKeyword: 'Keyword or phrase',
    setRulesKeywordHint: 'Khmer, Khmerlish or English. Matching ignores case.',
    setRulesSeverity: 'Severity',
    setRulesHarmfulHint: 'A matching comment is deleted from the Page automatically, without review.',
    setRulesOffensiveHint: 'Sent to the review queue for a person to decide.',
    setRulesSaving: 'Saving…',
    setRulesCount: (n: number) => `${n} keyword${n === 1 ? '' : 's'}`,
    setRulesSeeAll: 'See all keywords',
    setRulesHideAll: 'Done',
    setRulesMore: (n: number) => `+${n} more`,
    setRulesRemove: 'Remove',
    setRulesEmpty: 'No keywords yet. The shipped Khmer patterns still apply to every comment.',
    setRulesDuplicate: 'That keyword is already on this workspace’s list.',
    setRulesFailed: 'That keyword could not be saved. Please try again.',
    connTitle: 'Pages & Team',
    connLead: 'Connected Facebook Pages, plan capacity and the people who can moderate them.',
    connTabPages: 'Pages',
    connTabTeam: 'Team',
    connCapacity: 'Plan capacity',
    connPagesUsed: 'Pages connected',
    connSlots: 'Page slots',
    connEmptyPages: 'No Facebook Page is connected yet',
    connEmptyPagesLead: 'Connect a Page to start collecting comments for moderation.',
    connOpenSlot: 'Open slot',
    connTeamEmpty: 'No members yet',
    connTeamEmptyLead: 'Invite a teammate to review comments alongside you.',
    connInviteOpen: 'Open invitations',
    connInviteNone: 'No invitation is waiting to be accepted.',
    dashPageStatus: 'Demo page',
    dashPageConnected: 'Sample data',
    dashOverviewTitle: 'Overview',
    dashOverviewSubtitle: 'Current moderation metrics, risk categories, and Page activity.',
    dashLiveStatus: 'Moderation status',
    dashRecentIncidents: 'Recent High-Priority Comments',
    dashRecentIncidentsDesc: 'Latest comments surfaced for immediate moderator review.',
    dashNoRecentIncidents: 'No pending incidents. All comments are clear!',
    dashViewAllQueue: 'Open full queue',
    dashPageHealthTitle: 'Connected Facebook Pages',
    dashSyncActive: 'Connected and ready to synchronize',
    dashManagePages: 'Manage Pages',
    dashQuickShortcuts: 'Quick Navigation',
    dashShortcutRules: 'Triage Rules & Settings',
    dashShortcutTeam: 'Team Members & Access',
    dashProcessed: 'Comments processed',
    dashNeedReview: 'Need review',
    dashReviewed: 'Reviewed',
    dashPending: 'Pending',
    dashBreakdown: 'Why comments surfaced',
    dashOutcomes: 'Moderation outcomes',
    dashNoOutcomes: 'No actions recorded yet.',
    dashLeft: 'Left visible', dashDeleted: 'Deleted',
    dashOpenModerate: 'Review comments',
    openDemo: 'Open the demo',
    backHome: 'Back to home',
    requestTitle: 'Pilot access is by invitation',
    requestBody: 'KCMS is onboarding a small number of Cambodian organizations. Request access first; after review, KCMS sends a one-time link for creating your password.',
    requestDemoHint: 'Already approved? Use the sign-in page with the credentials you created from your invitation.',
    authSignInLead: 'Sign in to your moderation workspace.',
    authAccessPrompt: 'New to KCMS?',
    errName: 'Please enter your name.',
    errEmail: 'Please enter a valid email address.',
    errPasswordShort: 'Use at least 8 characters.',
    errPasswordRequired: 'Please enter your password.',
    errSummary: 'Please fix the following:',
    setSamples: 'Sample comments',
    setSamplesLead: 'This workspace was created with sample Khmer comments so the moderation screens had something to show. Once a real Facebook Page is connected they are only noise — removing them leaves the work list empty until the first sync.',
    setSamplesCount: (n: number) => `${n} sample comment${n === 1 ? '' : 's'} stored.`,
    setSamplesRemove: 'Remove sample comments',
    setSamplesConfirm: 'Remove the sample comments permanently? Comments imported from a connected Page are not affected.',
    setSamplesYes: 'Remove them',
    setSamplesCancel: 'Keep them',
    setSamplesClearing: 'Removing…',
    setSamplesDone: (n: number) => `Removed ${n} sample comment${n === 1 ? '' : 's'}.`,
    setSamplesError: 'The sample comments could not be removed. Please try again.',
    sandboxTitle: 'Demo workspace',
    sandboxBody: 'These are sample Khmer comments. You can connect an authorized Facebook Page from Page Connection.',
    sandboxCta: 'Connect Facebook Page',
    authSignIn: 'Sign in',
    authEmail: 'Email', authPassword: 'Password',
    authSignInTitle: 'Sign in to KCMS',
    authTelegram: 'Continue with Telegram',
    authOr: 'or',
    authWorking: 'Please wait…',
    authFailed: 'Email or password is incorrect.',
    authUnreachable: 'Could not reach KCMS. Please try again.',
    authSignOut: 'Sign out',
    authSignedInAs: 'Signed in as',
    signInTitle: 'Sign-in is not enabled yet',
    signInBody: 'The prototype does not have accounts. The moderation workspace is open so you can see how KCMS routes Khmer comments.',
    notFoundTitle: 'This page does not exist yet',
    notFoundBody: 'KCMS is an early prototype. Only the public site and the moderation workspace are built.',
    colComment: 'Comment', colSeverity: 'Severity', colTarget: 'Target',
    colReason: 'Why surfaced', colStatus: 'Status', colActions: 'Actions',
    statusPending: 'Pending', statusDone: 'Actioned',
    pagePrev: 'Previous', pageNext: 'Next',
    pageOf: 'of', pageShowing: 'Showing',
    rowExpand: 'Open', rowCollapse: 'Close',
    modTitle: 'Moderate',
    modSubtitle: 'Comments KCMS surfaced for your team.',
    modBackToSite: 'Back to site',
    modLoading: 'Loading comments…',
    modWaking: 'Waking the service — the free plan sleeps when idle. This can take up to a minute.',
    modErrorTitle: 'Could not reach KCMS',
    modErrorBody: 'The moderation service did not respond. Nothing has been changed.',
    modRetry: 'Try again',
    modEmpty: 'Nothing needs review right now.',
    modWhySurfaced: 'Why this surfaced',
    modConfidence: 'Confidence',
    modCorrect: 'Correct the label',
    modCorrectCancel: 'Cancel',
    modCorrectSave: 'Save correction',
    modCorrectHint: 'This records what the label should be. It does not delete or restore the comment.',
    modCorrectSeverity: 'Severity',
    modCorrectTarget: 'Target',
    modCorrected: 'Corrected to',
    modLeave: 'Leave visible',
    modHide: 'Hide',
    modUnhide: 'Unhide',
    modDelete: 'Delete',
    modDeleteConfirm: 'Delete permanently',
    modCancel: 'Cancel',
    modActioned: 'Last action',
    modBy: 'by',
    modReasons: {
      triage: 'Possible harm — review first',
      institution_sample: 'Aimed at an organization — never hidden automatically',
      novel_language: 'Unfamiliar wording — KCMS did not recognise this',
      uncertainty: 'Low confidence — a human decides',
      cleared: 'No risk pattern matched',
    },
    modSeverity: { SAFE: 'Safe', OFFENSIVE: 'Offensive', HARMFUL: 'Harmful' },
    modTarget: { PERSON: 'Person', INSTITUTION: 'Institution', NEITHER: 'No clear target' },
    modAbstain: 'Abstained',
    modCounts: 'comments',
    khmerEyebrow: 'Built for Khmer',
    khmerHeading: 'Khmer, Khmerlish, and the slang in between.',
    khmerDescription: 'Most moderation tools read Khmer as noise. KCMS matches Khmer script, romanized Khmerlish, everyday slang, misspellings, and deliberately obfuscated words — then separates who the comment is aimed at.',
    khmerCoverageLabel: 'Pattern matching covers',
    khmerCoverage: ['Khmer script', 'Khmerlish and code-switching', 'Everyday slang', 'Misspellings and obfuscated words'],
    khmerExamplesLabel: 'Same frustration, different target',
    khmerExamples: [
      {
        comment: 'សេវាកម្មក្រុមហ៊ុននេះយឺតណាស់ ខកចិត្តខ្លាំង។',
        gloss: '“This company’s service is so slow. Very disappointed.”',
        target: 'Institution',
        outcome: 'Stays visible',
        note: 'Criticism of an organization is protected. KCMS never removes it automatically.',
        tone: 'safe',
      },
      {
        comment: 'អ្នកនេះល្ងង់ណាស់ កុំឱ្យវានិយាយ។',
        gloss: '“This person is so stupid. Don’t let them speak.”',
        target: 'Person',
        outcome: 'Needs review',
        note: 'Person-directed abuse is surfaced so your team can decide what happens.',
        tone: 'review',
      },
    ],
    controlEyebrow: 'Human control',
    controlHeading: 'You decide what KCMS is allowed to do.',
    controlDescription: 'Detection runs automatically on every comment. What happens next is your team’s decision — and some limits stay in place no matter what you switch on.',
    controlGuarantees: [
      'Automatic hiding is off today. Every hide and unhide is performed by a person on your team.',
      'Actions are reversible, and the record shows who did what.',
      'Correcting a model label is separate from hiding a comment.',
      'Criticism aimed at an organization is never hidden automatically — at any confidence, under any setting.',
      'The model is frozen between releases. Your corrections feed the next training round, reviewed offline — never live.',
    ],
    controlScopeLabel: 'Current scope',
    controlScope: 'Facebook Page comments only. Messenger and Instagram are not connected yet.',
    accessEyebrow: 'Early access',
    accessHeading: 'Start a pilot with your Page and your team.',
    accessDescription: 'KCMS is onboarding a small number of Cambodian organizations. We review each pilot around its connected Facebook Pages and moderation workflow.',
    pricingPlans: [
      {
        id: 'starter',
        name: 'Starter',
        pagesLabel: 'Up to 3 Facebook Pages',
        price: '$15/mo',
        priceDetail: '$5 per Page',
        featuresLabel: 'Included with Starter:',
        features: [
          'Up to 3 Facebook Page connections',
          'Khmer & Khmerlish comment moderation',
          '2 moderator team seats included',
          'Single-click Leave, Hide & Unhide actions',
          '7-day moderation audit history',
          'Standard email support',
        ],
        cta: 'Request pilot access',
        isCustom: false,
      },
      {
        id: 'growth',
        name: 'Growth',
        pagesLabel: 'Up to 10 Facebook Pages',
        price: '$35/mo',
        priceDetail: '$3.50 per Page',
        featuresLabel: 'Everything in Starter, plus:',
        features: [
          'Up to 10 Facebook Page connections',
          'Full Khmer & Khmerlish moderation engine',
          'Unlimited team seats + role permissions',
          'Human label corrections for model training',
          '30-day extended audit log & CSV export',
          'Priority Telegram & email onboarding support',
        ],
        cta: 'Request pilot access',
        isCustom: false,
      },
      {
        id: 'enterprise',
        name: 'Enterprise',
        pagesLabel: 'Unlimited Facebook Pages',
        price: 'Custom annual quote',
        priceDetail: 'Tailored SLA & deployment',
        featuresLabel: 'Enterprise capabilities:',
        features: [
          'Unlimited Facebook Page connections',
          'Full Khmer & Khmerlish moderation engine',
          'Custom vocabulary & domain-specific tuning',
          'Unlimited seats + SSO / SAML integration',
          'Permanent audit trail & compliance export',
          'Dedicated Account Manager & 24/7 SLA',
        ],
        cta: 'Talk to sales',
        isCustom: true,
      },
    ],
    pricingBillingNote: 'Sellers and news outlets pay monthly. Institutions on the Enterprise plan pay annually.',
    pricingUpgradeNote: 'Price per Page drops as you grow — a natural upgrade path instead of a steep jump.',
    faqEyebrow: 'FAQ',
    faqHeading: 'Questions before connecting a Page.',
    faqDescription: 'Clear answers about automation, Facebook access, learning, and the current pilot.',
    faqItems: [
      {
        question: 'Does KCMS automatically detect comments?',
        answer: 'Yes. Detection and prioritization are automatic. Pattern matching powers the current prototype; a trained Khmer model will replace it after offline training and evaluation.',
      },
      {
        question: 'Does KCMS automatically hide or delete comments?',
        answer: 'Automatic hiding is currently off. A moderator decides whether to leave, hide, or unhide each surfaced comment.',
      },
      {
        question: 'What languages does KCMS support?',
        answer: 'KCMS focuses on Khmer, Khmerlish, everyday slang, misspellings, code-switching, and deliberately obfuscated wording.',
      },
      {
        question: 'Do I need Facebook Developer knowledge?',
        answer: 'No. Clients connect an authorized Page through KCMS, while the platform handles the technical integration.',
      },
      {
        question: 'How do corrections improve KCMS?',
        answer: 'Explicit corrections become candidates for a reviewed future training round. They never retrain or change the live system automatically.',
      },
      {
        question: 'Does KCMS use every client comment for training?',
        answer: 'No. Customer comments remain operational data by default. Dataset use requires permission, explicit labels, curation, and privacy review.',
      },
      {
        question: 'Does KCMS support Messenger or Instagram?',
        answer: 'Not currently. The initial product focuses on Facebook Page comments.',
      },
      {
        question: 'How much does KCMS cost?',
        answer: 'KCMS is currently onboarding pilot organizations. Future pricing may depend on the number of connected Facebook Pages. Contact us to discuss pilot access.',
      },
    ],
    footerNavLabel: 'Footer navigation',
    footerTagline: 'Khmer-first Facebook comment moderation, with humans in control of every action.',
    footerProduct: 'Product',
    footerAccess: 'Access',
    footerInformation: 'Information',
    footerContact: 'Contact',
    footerPrivacy: 'Privacy',
    footerStatusLabel: 'Prototype status',
    footerStatus: 'Versioned pattern matching · Human review required',
    footerRights: '© 2026 KCMS',
  },
  km: {
    howItWorks: 'របៀបដំណើរការ', signIn: 'ចូលប្រើ', language: 'English',
    eyebrow: 'ការគ្រប់គ្រងមតិយោបល់ខ្មែរជាចម្បង',
    heading: 'គ្រប់គ្រងមតិយោបល់ខ្មែរ ដោយយល់ពីបរិបទ មិនមែនការស្មាន។',
    description: 'ស្វែងរកមតិយោបល់បង្កគ្រោះថ្នាក់ និងការបោកប្រាស់បានលឿនជាងមុន។ KCMS ជួយក្រុមរបស់អ្នកកំណត់អាទិភាព ខណៈមនុស្សជាអ្នកសម្រេចចិត្តលើសកម្មភាពគ្រប់យ៉ាង។',
    requestAccess: 'ស្នើសុំប្រើប្រាស់', seeHow: 'មើលរបៀបដំណើរការ',
    pathwayLabel: 'របៀបដែលមតិយោបល់ទៅដល់ការពិនិត្យដោយមនុស្ស', incoming: 'មតិយោបល់លើទំព័រ Facebook',
    sampleComment: 'ចុចតំណនេះទទួលលុយ $500 ថ្ងៃនេះ!', pattern: 'ការរកឃើញស្វ័យប្រវត្តិ',
    patternDetail: 'ការផ្គូផ្គងលំនាំ · v0.1', review: 'ត្រូវការមនុស្សពិនិត្យ',
    reviewDetail: 'អាចជាសញ្ញាបោកប្រាស់', human: 'ក្រុមរបស់អ្នកជាអ្នកសម្រេច',
    humanDetail: 'ទុក · លាក់ · បើកលាក់វិញ · កែស្លាក', noAutomatic: 'រកឃើញស្វ័យប្រវត្តិ · មនុស្សអនុម័តសកម្មភាពលើទំព័រ',
    facebook: 'មតិយោបល់ Facebook', languageSupport: 'ខ្មែរ + Khmerlish', humanControlled: 'គ្រប់គ្រងដោយមនុស្ស',
    overviewEyebrow: 'ទិដ្ឋភាពទូទៅនៃសេវាកម្ម',
    overviewHeading: 'មើលមតិយោបល់ Facebook មួយឆ្លងកាត់ KCMS។',
    overviewDescription: 'មតិយោបល់ត្រូវបានរកឃើញដោយស្វ័យប្រវត្តិ ពិនិត្យដោយមនុស្ស ហើយលាក់ ឬបើកលាក់វិញលើទំព័រដែលបានភ្ជាប់។ ការបង្ហាញគំរូនេះនឹងត្រូវជំនួសដោយវីដេអូនៃដំណើរការពិតដែលបានផ្ទៀងផ្ទាត់។',
    overviewDemoCta: 'បើកកន្លែងធ្វើការរបស់អតិថិជន',
    overviewLoopLabel: 'ការបង្ហាញគំរូ',
    overviewPause: 'ផ្អាកចលនា',
    overviewPlay: 'ចាប់ផ្តើមចលនា',
    overviewVideoUnsupported: 'កម្មវិធីរុករករបស់អ្នកមិនអាចចាក់វីដេអូនេះបានទេ។',
    overviewTranscriptLabel: 'សេចក្ដីសង្ខេបនៃទិដ្ឋភាពសេវាកម្ម',
    overviewChapters: [
      'មតិយោបល់បានបង្ហោះលើ Facebook',
      'ការរកឃើញស្វ័យប្រវត្តិ',
      'ការពិនិត្យដោយមនុស្ស',
      'Facebook បានបញ្ជាក់ការលាក់',
      'បើកលាក់វិញ ដើម្បីស្តារមតិយោបល់',
    ],
    workflowEyebrow: 'ជំហានច្បាស់ ៣',
    workflowHeading: 'ពីមតិយោបល់ Facebook ទៅការសម្រេចដោយមនុស្ស។',
    workflowDescription: 'KCMS រក្សាជំនាន់ដំបូងឱ្យសាមញ្ញ៖ ភ្ជាប់ទំព័រ បង្ហាញមតិយោបល់ដែលត្រូវការយកចិត្តទុកដាក់ ហើយឱ្យក្រុមរបស់អ្នកសម្រេចសកម្មភាព។ បុគ្គលិកអតិថិជនមិនចាំបាច់ប្រើ Facebook Developer ដោយផ្ទាល់។',
    workflowSteps: [
      {
        title: 'ភ្ជាប់ទំព័រ',
        body: 'Client ភ្ជាប់ Facebook Page ម្តង។ KCMS បង្ហាញស្ថានភាពភ្ជាប់ ដើម្បីឱ្យក្រុមដឹងថាមតិយោបល់នៅតែចូលមកឬអត់។',
        meta: 'ការរៀបចំ',
      },
      {
        title: 'កំណត់អាទិភាពពិនិត្យ',
        body: 'ការផ្គូផ្គងលំនាំមានកំណែ ជួយចាប់សញ្ញាខ្មែរ ពាក្យស្លែង Khmerlish ការបោកប្រាស់ និងពាក្យបង្កគ្រោះថ្នាក់ ខណៈរក្សាការរិះគន់ធម្មតា។',
        meta: 'Pattern matching v0.1',
      },
      {
        title: 'សម្រេចដោយមានបរិបទ',
        body: 'Client ដែលទុកចិត្តអាចទុក លាក់ បើកលាក់វិញ ឬកែស្លាក។ សកម្មភាព និងស្លាកត្រូវបានរក្សាផ្សេងគ្នាសម្រាប់ការរៀនពេលក្រោយ។',
        meta: 'គ្រប់គ្រងដោយមនុស្ស',
      },
    ],
    navHumanControl: 'ការគ្រប់គ្រងដោយមនុស្ស',
    setTitle: 'ការកំណត់', setLead: 'កន្លែងធ្វើការ និងគណនីរបស់អ្នក។',
    setWorkspace: 'កន្លែងធ្វើការ', setWorkspaceName: 'ឈ្មោះកន្លែងធ្វើការ',
    setWorkspaceOwnerOnly: 'មានតែម្ចាស់ទេដែលអាចប្តូរឈ្មោះកន្លែងធ្វើការ។',
    setYou: 'អ្នក', setYourName: 'ឈ្មោះបង្ហាញរបស់អ្នក',
    setNameNote: 'បង្ហាញលើសកម្មភាពដែលអ្នកធ្វើចាប់ពីពេលនេះ។ សកម្មភាពពីមុនរក្សាឈ្មោះដែលអ្នកប្រើពេលនោះ។',
    setSave: 'រក្សាទុក', setSaved: 'បានរក្សាទុក', setSaving: 'កំពុងរក្សាទុក…',
    setPlan: 'ប្រភេទកន្លែងធ្វើការ', setSandbox: 'កន្លែងសាកល្បង', setConnected: 'បានអនុម័ត',
    setSignOut: 'ចាកចេញពី KCMS',
    errNameRequired: 'សូមបញ្ចូលឈ្មោះ។',
    teamTitle: 'ក្រុម', teamLead: 'អ្នកដែលអាចពិនិត្យក្នុងកន្លែងធ្វើការនេះ។',
    teamYou: 'អ្នក', teamOwner: 'ម្ចាស់', teamMember: 'សមាជិក',
    teamInvite: 'បង្កើតតំណអញ្ជើញ',
    teamInviteRole: 'ចូលរួមជា',
    teamLinkTitle: 'ចែករំលែកតំណនេះ',
    teamLinkBody: 'វាដំណើរការតែម្តង ហើយផុតកំណត់ក្នុង ៧ ថ្ងៃ។ យើងមិនអាចបង្ហាញវាម្តងទៀតទេ សូមចម្លងឥឡូវនេះ។',
    teamCopy: 'ចម្លងតំណ', teamCopied: 'បានចម្លង',
    teamOpenInvites: 'តំណអញ្ជើញដែលនៅសល់', teamRevoke: 'ដកហូត',
    teamExpires: 'ផុតកំណត់', teamRemove: 'ដកចេញ', teamPending: 'កំពុងរង់ចាំ',
    teamLastOwner: 'កន្លែងធ្វើការត្រូវមានម្ចាស់យ៉ាងតិចម្នាក់។ សូមតែងតាំងម្ចាស់ថ្មីជាមុនសិន។',
    teamLeave: 'ចាកចេញពីកន្លែងធ្វើការនេះ',
    teamLeaveConfirm: 'ចាកចេញពីកន្លែងធ្វើការនេះមែនទេ? អ្នកនឹងលែងឃើញមតិយោបល់របស់វា ហើយមានតែម្ចាស់ប៉ុណ្ណោះអាចបន្ថែមអ្នកមកវិញ។',
    teamLeaveYes: 'ចាកចេញ',
    teamLeaveError: 'មិនអាចដកអ្នកចេញពីកន្លែងធ្វើការនេះបានទេ។ សូមព្យាយាមម្ដងទៀត។',
    teamOwnerOnly: 'មានតែម្ចាស់ទេដែលអាចអញ្ជើញ ឬដកចេញបាន។',
    joinTitle: 'ចូលរួម', joinRole: 'អ្នកនឹងចូលរួមជា',
    joinAccept: 'ចូលរួមកន្លែងធ្វើការ', joinSignInFirst: 'សូមចូលប្រើដើម្បីទទួលយកការអញ្ជើញនេះ',
    joinInvalid: 'ការអញ្ជើញនេះមិនត្រឹមត្រូវ ផុតកំណត់ ឬបានប្រើរួចហើយ។',
    joinDone: 'អ្នកបានចូលរួម',
    adminTitle: 'សំណើចូលប្រើ', adminOps: 'ប្រតិបត្តិការវេទិកា',
    adminPending: 'រង់ចាំ', adminAll: 'ទាំងអស់', adminEmpty: 'គ្មានសំណើនៅពេលនេះទេ។',
    adminApprove: 'អនុម័ត', adminDecline: 'បដិសេធ',
    adminReason: 'មូលហេតុនៃការបដិសេធ', adminReasonHint: 'អតិថិជននឹងឃើញអត្ថបទនេះ។',
    adminConfirmDecline: 'បញ្ជាក់ការបដិសេធ', adminCancel: 'បោះបង់',
    adminMonthly: 'មតិយោបល់/ខែ', adminModerators: 'អ្នកពិនិត្យ',
    navAdmin: 'ការគ្រប់គ្រងវេទិកា',
    dashWorkspace: 'កន្លែងធ្វើការអតិថិជន',
    dashNavOverview: 'ទិដ្ឋភាពរួម',
    dashNavModerate: 'ពិនិត្យ',
    dashNavPage: 'ការគ្រប់គ្រង',
    dashNavTeam: 'ក្រុម',
    dashNavSettings: 'ការកំណត់',
    dashNavProfile: 'ប្រវត្តិរូប',
    dashNavRules: 'ច្បាប់ត្រួតពិនិត្យ',
    rulesTitle: 'ច្បាប់ត្រួតពិនិត្យ',
    rulesLead: 'ពាក្យដែលធ្វើឱ្យមតិយោបល់លេចឡើងសម្រាប់ការត្រួតពិនិត្យជានិច្ច ទោះសរសេរបែបណាក៏ដោយ។',
    rulesAddTitle: 'បន្ថែមពាក្យហាមឃាត់',
    rulesAddLead: 'ពាក្យនេះត្រូវបានបន្ថែមទៅបញ្ជីច្បាប់ ហើយអនុវត្តលើមតិយោបល់ដែលប្រមូលចាប់ពីពេលនេះ។',
    rulesWord: 'ពាក្យ ឬឃ្លា',
    rulesWordRequired: 'សូមបញ្ចូលពាក្យដែលត្រូវបន្ថែម។',
    rulesWordHint: 'ខ្មែរ Khmerlish ឬអង់គ្លេស។ ការផ្គូផ្គងមិនគិតអក្សរធំតូច និងវណ្ណយុត្តិជុំវិញទេ។',
    rulesSeverity: 'កម្រិតធ្ងន់ធ្ងរ',
    rulesNote: 'កំណត់ចំណាំ (មិនចាំបាច់)',
    rulesNoteHint: 'ហេតុអ្វីពាក្យនេះនៅក្នុងបញ្ជី។ បង្ហាញដល់អ្នកត្រួតពិនិត្យ មិនមែនសាធារណៈទេ។',
    rulesAdd: 'បន្ថែមពាក្យ',
    rulesAdding: 'កំពុងបន្ថែម…',
    rulesAdded: (word: string) => `បានបន្ថែម “${word}” ទៅបញ្ជីច្បាប់។`,
    rulesDuplicate: 'ពាក្យនេះមាននៅក្នុងបញ្ជីរួចហើយ។',
    rulesEmpty: 'មិនទាន់មានពាក្យហាមឃាត់ទេ',
    rulesEmptyLead: 'បន្ថែមពាក្យដំបូង នោះមតិយោបល់ថ្មីៗដែលមានពាក្យនោះនឹងលេចឡើងសម្រាប់ត្រួតពិនិត្យ។',
    rulesListTitle: 'ពាក្យហាមឃាត់បច្ចុប្បន្ន',
    rulesCount: (n: number) => `${n} ពាក្យ`,
    rulesSearch: 'ស្វែងរកពាក្យ',
    rulesNoMatch: 'គ្មានពាក្យត្រូវនឹងការស្វែងរកនោះទេ។',
    rulesRemove: 'ដកចេញ',
    rulesRemoveFailed: 'មិនអាចដកពាក្យនោះចេញបានទេ។ សូមព្យាយាមម្ដងទៀត។',
    rulesAddFailed: 'មិនអាចរក្សាទុកពាក្យនោះបានទេ។ សូមព្យាយាមម្ដងទៀត។',
    rulesUnavailable: 'ច្បាប់ត្រួតពិនិត្យមិនទាន់មានសម្រាប់កន្លែងធ្វើការនេះទេ។',
    rulesUnavailableLead: 'ចំណុចប្រទាក់បញ្ជីច្បាប់មិនទាន់ដំឡើងទេ។ ពាក្យដែលបន្ថែមនៅទីនេះមិនអាចរក្សាទុកបានទេ។',
    connAddTitle: 'បន្ថែមទំព័រ',
    connAddLead: 'ជ្រើសទំព័រដែលអ្នកគ្រប់គ្រង។ KCMS នឹងប្រមូលមតិយោបល់របស់វាសម្រាប់ត្រួតពិនិត្យ។',
    connAdd: 'បន្ថែមទំព័រ',
    connAdding: 'កំពុងបើក…',
    connAddFeature1: 'ទំព័រដែលអ្នកគ្រប់គ្រងត្រូវបានរកឃើញដោយស្វ័យប្រវត្តិ',
    connAddFeature2: 'ស្នើសុំតែសិទ្ធិគ្រប់គ្រងមតិយោបល់ប៉ុណ្ណោះ',
    connAddFeature3: 'អាចផ្ដាច់ទំព័រនៅពេលណាក៏បាន',
    connMethodFacebook: 'ទំព័រ Facebook',
    dashNotBuilt: 'មិនមានក្នុងគំរូ',
    proTitle: 'ប្រវត្តិរូប',
    proLead: 'អត្តសញ្ញាណរបស់អ្នកក្នុងកន្លែងធ្វើការនេះ និងរបៀបដែល KCMS ដំណើរការសម្រាប់អ្នក។',
    proIdentity: 'បានចូលជា',
    proAccount: 'គណនី',
    proAccountLead: 'របៀបដែលឈ្មោះអ្នកបង្ហាញលើគ្រប់សកម្មភាពគ្រប់គ្រងដែលអ្នកធ្វើ។',
    proDetails: 'ព័ត៌មានលម្អិតគណនី',
    proDetailsLead: 'ព័ត៌មានតែអានបាន អំពីគណនីនេះ និងកន្លែងធ្វើការរបស់វា។',
    proRole: 'តួនាទីក្នុងកន្លែងធ្វើការ',
    proWorkspace: 'កន្លែងធ្វើការ',
    proUserId: 'លេខសម្គាល់អ្នកប្រើ',
    proAccess: 'កម្រិតសិទ្ធិ',
    proAdmin: 'អ្នកគ្រប់គ្រងប្រព័ន្ធ',
    proStandard: 'អ្នកប្រើកន្លែងធ្វើការ',
    proPreferences: 'ចំណូលចិត្ត',
    proPreferencesLead: 'អនុវត្តតែលើកម្មវិធីរុករកនេះ។ គ្មានអ្វីត្រូវរក្សាទុកក្នុងកន្លែងធ្វើការទេ។',
    proLanguage: 'ភាសាប្រព័ន្ធ',
    proLanguageHint: 'ប្ដូរគ្រប់អេក្រង់រវាងភាសាអង់គ្លេស និងខ្មែរ។',
    proSession: 'វេនប្រើប្រាស់',
    proSessionLead: 'ការចាកចេញបញ្ចប់វេននេះតែលើឧបករណ៍នេះប៉ុណ្ណោះ។',
    proWorkspaceLink: 'ការកំណត់កន្លែងធ្វើការ',
    proWorkspaceLinkLead: 'ឈ្មោះកន្លែងធ្វើការ គម្រោង និងទិន្នន័យគំរូ ស្ថិតក្នុងការកំណត់។',
    proOpenSettings: 'បើកការកំណត់',
    setYouLead: 'ឈ្មោះបង្ហាញ និងចំណូលចិត្តរបស់អ្នក ត្រូវបានផ្លាស់ទៅប្រវត្តិរូប។',
    setOpenProfile: 'បើកប្រវត្តិរូប',
    setGeneral: 'ទូទៅ',
    setGeneralLead: 'ឈ្មោះដែលក្រុមរបស់អ្នកឃើញ និងប្រភេទកន្លែងធ្វើការនេះ។',
    setDangerZone: 'ទិន្នន័យ',
    setWorkspaceId: 'លេខសម្គាល់កន្លែងធ្វើការ',
    setNavGeneral: 'ទូទៅ',
    setNavData: 'ទិន្នន័យ',
    setNavProfile: 'គណនី',
    setNavRules: 'ច្បាប់',
    setRules: 'ច្បាប់ត្រួតពិនិត្យ',
    setRulesLead: 'ពាក្យគន្លឹះសម្រាប់កន្លែងធ្វើការនេះតែប៉ុណ្ណោះ។ កន្លែងធ្វើការផ្សេងមិនរងផលប៉ះពាល់ទេ។',
    setRulesAdd: 'បន្ថែមពាក្យគន្លឹះ',
    setRulesAddTitle: 'បន្ថែមពាក្យគន្លឹះ',
    setRulesAddLead: 'អនុវត្តលើមតិយោបល់ដែលប្រមូលចាប់ពីពេលនេះ ក្នុងកន្លែងធ្វើការនេះតែប៉ុណ្ណោះ។',
    setRulesListTitle: 'ពាក្យគន្លឹះរបស់អ្នក',
    setRulesListLead: 'បន្ថែមលើលំនាំខ្មែរដែល KCMS មានស្រាប់ ដែលអនុវត្តជានិច្ច។',
    setRulesEmptyTitle: 'មិនទាន់មានពាក្យគន្លឹះទេ',
    setRulesKeyword: 'ពាក្យគន្លឹះ ឬឃ្លា',
    setRulesKeywordHint: 'ខ្មែរ Khmerlish ឬអង់គ្លេស។ ការផ្គូផ្គងមិនគិតអក្សរធំតូចទេ។',
    setRulesSeverity: 'កម្រិតធ្ងន់ធ្ងរ',
    setRulesHarmfulHint: 'មតិយោបល់ដែលត្រូវគ្នា ត្រូវលុបចេញពីទំព័រដោយស្វ័យប្រវត្តិ ដោយគ្មានការត្រួតពិនិត្យ។',
    setRulesOffensiveHint: 'បញ្ជូនទៅជួរត្រួតពិនិត្យ ដើម្បីឱ្យមនុស្សសម្រេច។',
    setRulesSaving: 'កំពុងរក្សាទុក…',
    setRulesCount: (n: number) => `${n} ពាក្យគន្លឹះ`,
    setRulesSeeAll: 'មើលពាក្យគន្លឹះទាំងអស់',
    setRulesHideAll: 'រួចរាល់',
    setRulesMore: (n: number) => `+${n} ទៀត`,
    setRulesRemove: 'ដកចេញ',
    setRulesEmpty: 'មិនទាន់មានពាក្យគន្លឹះទេ។ លំនាំខ្មែរដើមនៅតែអនុវត្តលើគ្រប់មតិយោបល់។',
    setRulesDuplicate: 'ពាក្យគន្លឹះនេះមានក្នុងបញ្ជីរបស់កន្លែងធ្វើការនេះរួចហើយ។',
    setRulesFailed: 'មិនអាចរក្សាទុកពាក្យគន្លឹះនោះបានទេ។ សូមព្យាយាមម្ដងទៀត។',

    connTitle: 'ទំព័រ & ក្រុមការងារ',
    connLead: 'ទំព័រ Facebook ដែលបានភ្ជាប់ សមត្ថភាពគម្រោង និងអ្នកដែលអាចគ្រប់គ្រងពួកវា។',
    connTabPages: 'ទំព័រ',
    connTabTeam: 'ក្រុម',
    connCapacity: 'សមត្ថភាពគម្រោង',
    connPagesUsed: 'ទំព័របានភ្ជាប់',
    connSlots: 'កន្លែងទំព័រ',
    connEmptyPages: 'មិនទាន់មានទំព័រ Facebook ភ្ជាប់ទេ',
    connEmptyPagesLead: 'ភ្ជាប់ទំព័រមួយដើម្បីចាប់ផ្ដើមប្រមូលមតិយោបល់សម្រាប់ត្រួតពិនិត្យ។',
    connOpenSlot: 'កន្លែងទំនេរ',
    connTeamEmpty: 'មិនទាន់មានសមាជិកទេ',
    connTeamEmptyLead: 'អញ្ជើញសហការីម្នាក់ដើម្បីពិនិត្យមតិយោបល់ជាមួយអ្នក។',
    connInviteOpen: 'តំណអញ្ជើញដែលនៅសល់',
    connInviteNone: 'គ្មានតំណអញ្ជើញកំពុងរង់ចាំការទទួលយកទេ។',
    dashPageStatus: 'ទំព័រសាកល្បង',
    dashPageConnected: 'ទិន្នន័យគំរូ',
    dashOverviewTitle: 'ទិដ្ឋភាពរួម',
    dashOverviewSubtitle: 'ទិន្នន័យគ្រប់គ្រងមតិយោបល់បច្ចុប្បន្ន ប្រភេទហានិភ័យ និងសកម្មភាពទំព័រ។',
    dashLiveStatus: 'ស្ថានភាពគ្រប់គ្រងមតិយោបល់',
    dashRecentIncidents: 'មតិយោបល់អាទិភាពខ្ពស់ថ្មីៗ',
    dashRecentIncidentsDesc: 'មតិយោបល់ចុងក្រោយដែលទាមទារការពិនិត្យពីអ្នកសម្របសម្រួល។',
    dashNoRecentIncidents: 'គ្មានមតិយោបល់កំពុងរង់ចាំទេ។ ទាំងអស់ត្រូវបានដោះស្រាយរួចរាល់!',
    dashViewAllQueue: 'មើលជួររង់ចាំទាំងអស់',
    dashPageHealthTitle: 'Facebook Pages ដែលបានភ្ជាប់',
    dashSyncActive: 'បានភ្ជាប់ និងរួចរាល់សម្រាប់ធ្វើសមកាលកម្ម',
    dashManagePages: 'គ្រប់គ្រង Pages',
    dashQuickShortcuts: 'ផ្លូវកាត់រហ័ស',
    dashShortcutRules: 'វិធាន & ការកំណត់',
    dashShortcutTeam: 'សមាជិកក្រុម & សិទ្ធិ',
    dashProcessed: 'មតិយោបល់បានដំណើរការ',
    dashNeedReview: 'ត្រូវការពិនិត្យ',
    dashReviewed: 'បានពិនិត្យ',
    dashPending: 'កំពុងរង់ចាំ',
    dashBreakdown: 'ហេតុអ្វីមតិយោបល់បានបង្ហាញ',
    dashOutcomes: 'លទ្ធផលនៃការគ្រប់គ្រង',
    dashNoOutcomes: 'មិនទាន់មានសកម្មភាពត្រូវបានកត់ត្រាទេ។',
    dashLeft: 'ទុកឱ្យបង្ហាញ', dashDeleted: 'បានលុប',
    dashOpenModerate: 'ពិនិត្យមតិយោបល់',
    openDemo: 'បើកការសាកល្បង',
    backHome: 'ត្រឡប់ទៅទំព័រដើម',
    requestTitle: 'ការចូលរួមសាកល្បងតាមការអញ្ជើញ',
    requestBody: 'KCMS កំពុងទទួលអង្គការកម្ពុជាមួយចំនួនតូច។ សូមស្នើសុំចូលប្រើជាមុន។ បន្ទាប់ពីពិនិត្យ KCMS នឹងផ្ញើតំណប្រើម្តង ដើម្បីបង្កើតពាក្យសម្ងាត់។',
    requestDemoHint: 'បានអនុម័តរួចហើយ? សូមចូលប្រើដោយព័ត៌មានដែលអ្នកបានបង្កើតតាមតំណអញ្ជើញ។',
    authSignInLead: 'ចូលទៅកន្លែងធ្វើការពិនិត្យរបស់អ្នក។',
    authAccessPrompt: 'មិនទាន់មានគណនី KCMS?',
    errName: 'សូមបញ្ចូលឈ្មោះរបស់អ្នក។',
    errEmail: 'សូមបញ្ចូលអាសយដ្ឋានអ៊ីមែលត្រឹមត្រូវ។',
    errPasswordShort: 'ប្រើយ៉ាងតិច ៨ តួអក្សរ។',
    errPasswordRequired: 'សូមបញ្ចូលពាក្យសម្ងាត់របស់អ្នក។',
    errSummary: 'សូមកែខាងក្រោម៖',
    setSamples: 'មតិយោបល់គំរូ',
    setSamplesLead: 'កន្លែងធ្វើការនេះត្រូវបានបង្កើតជាមួយមតិយោបល់ខ្មែរគំរូ ដើម្បីឱ្យអេក្រង់គ្រប់គ្រងមានអ្វីបង្ហាញ។ ពេលភ្ជាប់ Facebook Page ពិតរួច ពួកវាគ្រាន់តែជាការរំខាន — ការលុបនឹងធ្វើឱ្យបញ្ជីទទេ រហូតដល់ការទាញយកលើកដំបូង។',
    setSamplesCount: (n: number) => `មានមតិយោបល់គំរូ ${n} ត្រូវបានរក្សាទុក។`,
    setSamplesRemove: 'លុបមតិយោបល់គំរូ',
    setSamplesConfirm: 'លុបមតិយោបល់គំរូជាអចិន្ត្រៃយ៍មែនទេ? មតិយោបល់ដែលនាំចូលពី Page ដែលបានភ្ជាប់ មិនរងផលប៉ះពាល់ទេ។',
    setSamplesYes: 'លុបចេញ',
    setSamplesCancel: 'រក្សាទុក',
    setSamplesClearing: 'កំពុងលុប…',
    setSamplesDone: (n: number) => `បានលុបមតិយោបល់គំរូ ${n}។`,
    setSamplesError: 'មិនអាចលុបមតិយោបល់គំរូបានទេ។ សូមព្យាយាមម្ដងទៀត។',
    sandboxTitle: 'កន្លែងធ្វើការសាកល្បង',
    sandboxBody: 'ទាំងនេះជាមតិយោបល់ខ្មែរគំរូ។ អ្នកអាចភ្ជាប់ Facebook Page ដែលមានសិទ្ធិពីផ្នែកភ្ជាប់ Page។',
    sandboxCta: 'ភ្ជាប់ Facebook Page',
    authSignIn: 'ចូលប្រើ',
    authEmail: 'អ៊ីមែល', authPassword: 'ពាក្យសម្ងាត់',
    authSignInTitle: 'ចូលប្រើ KCMS',
    authTelegram: 'បន្តជាមួយ Telegram',
    authOr: 'ឬ',
    authWorking: 'សូមរង់ចាំ…',
    authFailed: 'អ៊ីមែល ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ។',
    authUnreachable: 'មិនអាចភ្ជាប់ទៅ KCMS។ សូមព្យាយាមម្តងទៀត។',
    authSignOut: 'ចាកចេញ',
    authSignedInAs: 'ចូលប្រើជា',
    signInTitle: 'ការចូលប្រើមិនទាន់បើកនៅឡើយ',
    signInBody: 'គំរូនេះមិនទាន់មានគណនីទេ។ កន្លែងពិនិត្យមតិយោបល់បើកចំហ ដើម្បីឱ្យអ្នកឃើញរបៀបដែល KCMS បញ្ជូនមតិយោបល់ខ្មែរ។',
    notFoundTitle: 'ទំព័រនេះមិនទាន់មានទេ',
    notFoundBody: 'KCMS ជាគំរូដំបូង។ មានតែគេហទំព័រសាធារណៈ និងកន្លែងពិនិត្យមតិយោបល់ប៉ុណ្ណោះដែលបានសាង។',
    colComment: 'មតិយោបល់', colSeverity: 'កម្រិត', colTarget: 'គោលដៅ',
    colReason: 'ហេតុផល', colStatus: 'ស្ថានភាព', colActions: 'សកម្មភាព',
    statusPending: 'រង់ចាំ', statusDone: 'បានធ្វើ',
    pagePrev: 'មុន', pageNext: 'បន្ទាប់',
    pageOf: 'នៃ', pageShowing: 'បង្ហាញ',
    rowExpand: 'បើក', rowCollapse: 'បិទ',
    modTitle: 'ពិនិត្យមតិយោបល់',
    modSubtitle: 'មតិយោបល់ដែល KCMS បង្ហាញសម្រាប់ក្រុមរបស់អ្នក។',
    modBackToSite: 'ត្រឡប់ទៅគេហទំព័រ',
    modLoading: 'កំពុងទាញមតិយោបល់…',
    modWaking: 'កំពុងដាស់សេវាកម្ម — គម្រោងឥតគិតថ្លៃដេកនៅពេលទំនេរ។ អាចចំណាយពេលដល់មួយនាទី។',
    modErrorTitle: 'មិនអាចភ្ជាប់ទៅ KCMS',
    modErrorBody: 'សេវាកម្មពិនិត្យមិនបានឆ្លើយតប។ គ្មានអ្វីត្រូវបានផ្លាស់ប្តូរឡើយ។',
    modRetry: 'ព្យាយាមម្តងទៀត',
    modEmpty: 'គ្មានអ្វីត្រូវពិនិត្យនៅពេលនេះទេ។',
    modWhySurfaced: 'ហេតុអ្វីបានបង្ហាញ',
    modConfidence: 'កម្រិតជឿជាក់',
    modCorrect: 'កែស្លាក',
    modCorrectCancel: 'បោះបង់',
    modCorrectSave: 'រក្សាទុកការកែ',
    modCorrectHint: 'នេះកត់ត្រាថាស្លាកគួរជាអ្វី។ វាមិនលាក់ ឬបើកលាក់មតិយោបល់ឡើយ។',
    modCorrectSeverity: 'កម្រិតធ្ងន់ធ្ងរ',
    modCorrectTarget: 'គោលដៅ',
    modCorrected: 'បានកែទៅជា',
    modLeave: 'ទុកឱ្យបង្ហាញ',
    modHide: 'លាក់',
    modUnhide: 'បង្ហាញវិញ',
    modDelete: 'លុប',
    modDeleteConfirm: 'លុបជាអចិន្ត្រៃយ៍',
    modCancel: 'បោះបង់',
    modActioned: 'សកម្មភាពចុងក្រោយ',
    modBy: 'ដោយ',
    modReasons: {
      triage: 'អាចមានគ្រោះថ្នាក់ — ពិនិត្យមុន',
      institution_sample: 'សំដៅលើអង្គភាព — មិនលាក់ស្វ័យប្រវត្តិឡើយ',
      novel_language: 'ពាក្យមិនធ្លាប់ស្គាល់ — KCMS មិនអាចអានបាន',
      uncertainty: 'កម្រិតជឿជាក់ទាប — មនុស្សសម្រេច',
      cleared: 'គ្មានលំនាំហានិភ័យត្រូវគ្នា',
    },
    modSeverity: { SAFE: 'សុវត្ថិភាព', OFFENSIVE: 'ប្រមាថ', HARMFUL: 'បង្កគ្រោះថ្នាក់' },
    modTarget: { PERSON: 'បុគ្គល', INSTITUTION: 'អង្គភាព', NEITHER: 'គ្មានគោលដៅច្បាស់' },
    modAbstain: 'មិនសម្រេច',
    modCounts: 'មតិយោបល់',
    khmerEyebrow: 'សាងសម្រាប់ភាសាខ្មែរ',
    khmerHeading: 'ខ្មែរ Khmerlish និងពាក្យស្លែងនៅចន្លោះ។',
    khmerDescription: 'ឧបករណ៍គ្រប់គ្រងភាគច្រើនអានភាសាខ្មែរជាសំឡេងរំខាន។ KCMS ផ្គូផ្គងអក្សរខ្មែរ Khmerlish ពាក្យស្លែងប្រចាំថ្ងៃ ពាក្យសរសេរខុស និងពាក្យបំបាំង រួចបែងចែកថាមតិយោបល់នោះសំដៅលើនរណា។',
    khmerCoverageLabel: 'ការផ្គូផ្គងលំនាំគ្របដណ្តប់',
    khmerCoverage: ['អក្សរខ្មែរ', 'Khmerlish និងការលាយភាសា', 'ពាក្យស្លែងប្រចាំថ្ងៃ', 'ពាក្យសរសេរខុស និងពាក្យបំបាំង'],
    khmerExamplesLabel: 'ការខកចិត្តដូចគ្នា គោលដៅខុសគ្នា',
    khmerExamples: [
      {
        comment: 'សេវាកម្មក្រុមហ៊ុននេះយឺតណាស់ ខកចិត្តខ្លាំង។',
        gloss: '“សេវាកម្មរបស់ក្រុមហ៊ុននេះយឺតណាស់។ ខកចិត្តខ្លាំង។”',
        target: 'អង្គភាព',
        outcome: 'នៅតែបង្ហាញ',
        note: 'ការរិះគន់អង្គភាពត្រូវបានការពារ។ KCMS មិនលុបវាដោយស្វ័យប្រវត្តិឡើយ។',
        tone: 'safe',
      },
      {
        comment: 'អ្នកនេះល្ងង់ណាស់ កុំឱ្យវានិយាយ។',
        gloss: '“អ្នកនេះល្ងង់ណាស់។ កុំឱ្យគាត់និយាយ។”',
        target: 'បុគ្គល',
        outcome: 'ត្រូវការពិនិត្យ',
        note: 'ការវាយប្រហារសំដៅលើបុគ្គល ត្រូវបានបង្ហាញដល់ក្រុមរបស់អ្នកដើម្បីសម្រេច។',
        tone: 'review',
      },
    ],
    controlEyebrow: 'ការគ្រប់គ្រងដោយមនុស្ស',
    controlHeading: 'អ្នកជាអ្នកសម្រេចថា KCMS អាចធ្វើអ្វីបាន។',
    controlDescription: 'ការរកឃើញដំណើរការស្វ័យប្រវត្តិលើមតិយោបល់គ្រប់មួយ។ អ្វីដែលកើតឡើងបន្ទាប់ គឺជាការសម្រេចរបស់ក្រុមអ្នក ហើយដែនកំណត់មួយចំនួននៅតែមាន ទោះបីអ្នកបើកមុខងារណាក៏ដោយ។',
    controlGuarantees: [
      'ការលាក់ស្វ័យប្រវត្តិត្រូវបានបិទនៅពេលនេះ។ រាល់ការលាក់ និងការបើកលាក់វិញ ធ្វើឡើងដោយមនុស្សក្នុងក្រុមរបស់អ្នក។',
      'សកម្មភាពអាចត្រឡប់វិញបាន ហើយកំណត់ត្រាបង្ហាញថានរណាធ្វើអ្វី។',
      'ការកែស្លាកគំរូ ដាច់ដោយឡែកពីការលាក់មតិយោបល់។',
      'ការរិះគន់ដែលសំដៅលើអង្គភាព មិនត្រូវបានលាក់ដោយស្វ័យប្រវត្តិឡើយ ទោះកម្រិតជឿជាក់ណា ឬការកំណត់បែបណាក៏ដោយ។',
      'គំរូត្រូវបានបង្កកចន្លោះការចេញផ្សាយនីមួយៗ។ ការកែតម្រូវរបស់អ្នកចូលទៅក្នុងវគ្គហ្វឹកហាត់បន្ទាប់ ដែលពិនិត្យក្រៅប្រព័ន្ធ មិនមែនផ្ទាល់ឡើយ។',
    ],
    controlScopeLabel: 'វិសាលភាពបច្ចុប្បន្ន',
    controlScope: 'មតិយោបល់លើទំព័រ Facebook តែប៉ុណ្ណោះ។ Messenger និង Instagram មិនទាន់ភ្ជាប់នៅឡើយទេ។',
    accessEyebrow: 'ការចូលប្រើដំបូង',
    accessHeading: 'ចាប់ផ្តើមសាកល្បងជាមួយទំព័រ និងក្រុមរបស់អ្នក។',
    accessDescription: 'KCMS កំពុងទទួលអង្គការកម្ពុជាមួយចំនួនតូច។ យើងពិនិត្យការសាកល្បងតាម Facebook Page ដែលត្រូវភ្ជាប់ និងដំណើរការគ្រប់គ្រងមតិយោបល់។',
    pricingPlans: [
      {
        id: 'starter',
        name: 'ចាប់ផ្តើម',
        pagesLabel: 'រហូតដល់ ៣ ទំព័រ Facebook',
        price: '$15/ខែ',
        priceDetail: '$5/ទំព័រ',
        featuresLabel: 'មុខងាររួមបញ្ចូលក្នុង Starter៖',
        features: [
          'ភ្ជាប់ទំព័រ Facebook បានរហូតដល់ ៣ ទំព័រ',
          'ការគ្រប់គ្រងមតិយោបល់ខ្មែរ និង Khmerlish ភ្លាមៗ',
          'គណនីអ្នកពិនិត្យក្នុងក្រុម ២ នាក់',
          'ចាត់ការ ទុក លាក់ និងបើកលាក់វិញ ដោយចុចម្តង',
          'ប្រវត្តិកំណត់ត្រាការពិនិត្យរយៈពេល ៧ ថ្ងៃ',
          'ជំនួយបច្ចេកទេសតាមអ៊ីមែលស្តង់ដារ',
        ],
        cta: 'ស្នើសុំការចូលប្រើសាកល្បង',
        isCustom: false,
      },
      {
        id: 'growth',
        name: 'រីកចម្រើន',
        pagesLabel: 'រហូតដល់ ១០ ទំព័រ Facebook',
        price: '$35/ខែ',
        priceDetail: '$3.50/ទំព័រ',
        featuresLabel: 'រួមបញ្ចូលអ្វីៗពី Starter បូកបន្ថែម៖',
        features: [
          'ភ្ជាប់ទំព័រ Facebook បានរហូតដល់ ១០ ទំព័រ',
          'ប្រព័ន្ធគ្រប់គ្រងមតិយោបល់ខ្មែរពេញលេញ',
          'គណនីអ្នកពិនិត្យមិនកំណត់ + កំណត់សិទ្ធិក្រុម',
          'ការកែស្លាកដោយមនុស្សដើម្បីកែលម្អប្រព័ន្ធ',
          'ប្រវត្តិកំណត់ត្រា ៣០ ថ្ងៃ និងការទាញយក CSV',
          'ជំនួយអាទិភាពតាមអ៊ីមែល និង Telegram',
        ],
        cta: 'ស្នើសុំការចូលប្រើសាកល្បង',
        isCustom: false,
      },
      {
        id: 'enterprise',
        name: 'សហគ្រាស',
        pagesLabel: 'ទំព័រ Facebook មិនកំណត់',
        price: 'សម្រង់តម្លៃប្រចាំឆ្នាំតាមតម្រូវការ',
        priceDetail: 'ការដាក់ពង្រាយ និង SLA តាមតម្រូវការ',
        featuresLabel: 'សមត្ថភាពកម្រិតសហគ្រាស៖',
        features: [
          'ភ្ជាប់ទំព័រ Facebook បានមិនកំណត់',
          'ប្រព័ន្ធគ្រប់គ្រងមតិយោបល់ខ្មែរពេញលេញ',
          'វចនានុក្រមតាមវិស័យ និងការកែសម្រួលគំរូផ្ទាល់ខ្លួន',
          'គណនីក្រុមមិនកំណត់ + ការតភ្ជាប់ SSO / SAML',
          'ប្រវត្តិកំណត់ត្រាអចិន្ត្រៃយ៍ និងរបាយការណ៍អនុលោមភាព',
          'អ្នកគ្រប់គ្រងគណនីផ្ទាល់ និងការគាំទ្រ SLA ២៤/៧',
        ],
        cta: 'ទាក់ទងផ្នែកលក់',
        isCustom: true,
      },
    ],
    pricingBillingNote: 'អ្នកលក់ និងការិយាល័យព័ត៌មានបង់ប្រាក់ប្រចាំខែ។ ស្ថាប័នដែលប្រើគម្រោង Enterprise បង់ប្រាក់ប្រចាំឆ្នាំ។',
    pricingUpgradeNote: 'តម្លៃក្នុងមួយទំព័រថយចុះនៅពេលអ្នកកាន់តែរីកចម្រើន — ជាផ្លូវឡើងកម្រិតដោយធម្មជាតិ មិនមែនការលោតដល់តម្លៃខ្ពស់ភ្លាមៗទេ។',
    faqEyebrow: 'សំណួរញឹកញាប់',
    faqHeading: 'សំណួរមុនពេលភ្ជាប់ទំព័រ។',
    faqDescription: 'ចម្លើយច្បាស់លាស់អំពីស្វ័យប្រវត្តិកម្ម ការចូលប្រើ Facebook ការរៀនរបស់ប្រព័ន្ធ និងការសាកល្បងបច្ចុប្បន្ន។',
    faqItems: [
      {
        question: 'តើ KCMS រកឃើញមតិយោបល់ដោយស្វ័យប្រវត្តិទេ?',
        answer: 'បាទ/ចាស។ ការរកឃើញ និងការកំណត់អាទិភាពដំណើរការដោយស្វ័យប្រវត្តិ។ Prototype បច្ចុប្បន្នប្រើការផ្គូផ្គងលំនាំ ហើយគំរូភាសាខ្មែរដែលបានបណ្តុះបណ្តាលនឹងជំនួសវាបន្ទាប់ពីការបណ្តុះបណ្តាល និងវាយតម្លៃក្រៅប្រព័ន្ធ។',
      },
      {
        question: 'តើ KCMS លាក់ ឬលុបមតិយោបល់ដោយស្វ័យប្រវត្តិទេ?',
        answer: 'ការលាក់ដោយស្វ័យប្រវត្តិត្រូវបានបិទនៅពេលនេះ។ អ្នកគ្រប់គ្រងជាអ្នកសម្រេចថាត្រូវទុក លាក់ ឬបើកលាក់មតិយោបល់នីមួយៗវិញ។',
      },
      {
        question: 'តើ KCMS គាំទ្រភាសាអ្វីខ្លះ?',
        answer: 'KCMS ផ្តោតលើភាសាខ្មែរ Khmerlish ពាក្យស្លែង ការសរសេរខុស ការលាយភាសា និងពាក្យដែលត្រូវបានកែប្រែដើម្បីគេចពីការរកឃើញ។',
      },
      {
        question: 'តើខ្ញុំត្រូវចេះ Facebook Developer ទេ?',
        answer: 'មិនចាំបាច់ទេ។ អតិថិជនភ្ជាប់ទំព័រដែលមានសិទ្ធិតាម KCMS ហើយ Platform ជាអ្នកគ្រប់គ្រងការភ្ជាប់បច្ចេកទេស។',
      },
      {
        question: 'តើការកែស្លាកជួយកែលម្អ KCMS ដូចម្តេច?',
        answer: 'ការកែស្លាកច្បាស់លាស់អាចក្លាយជាទិន្នន័យសម្រាប់វគ្គបណ្តុះបណ្តាលបន្ទាប់ បន្ទាប់ពីការពិនិត្យ។ វាមិនបណ្តុះបណ្តាល ឬប្តូរប្រព័ន្ធដែលកំពុងដំណើរការដោយស្វ័យប្រវត្តិទេ។',
      },
      {
        question: 'តើ KCMS ប្រើមតិយោបល់អតិថិជនទាំងអស់សម្រាប់បណ្តុះបណ្តាលទេ?',
        answer: 'ទេ។ មតិយោបល់អតិថិជនជាទិន្នន័យប្រតិបត្តិការតាមលំនាំដើម។ ការប្រើសម្រាប់ Dataset ត្រូវការការអនុញ្ញាត ស្លាកច្បាស់លាស់ ការជ្រើសរើស និងការពិនិត្យឯកជនភាព។',
      },
      {
        question: 'តើ KCMS គាំទ្រ Messenger ឬ Instagram ទេ?',
        answer: 'មិនទាន់ទេ។ ផលិតផលដំបូងផ្តោតលើមតិយោបល់ Facebook Page។',
      },
      {
        question: 'តើ KCMS មានតម្លៃប៉ុន្មាន?',
        answer: 'KCMS កំពុងទទួលអង្គការសាកល្បង។ តម្លៃនាពេលអនាគតអាចអាស្រ័យលើចំនួន Facebook Page ដែលបានភ្ជាប់។ សូមទាក់ទងយើងដើម្បីពិភាក្សាអំពីការចូលប្រើសាកល្បង។',
      },
    ],
    footerNavLabel: 'ការរុករកផ្នែកខាងក្រោម',
    footerTagline: 'ការគ្រប់គ្រងមតិយោបល់ Facebook ជាភាសាខ្មែរ ដោយមនុស្សគ្រប់គ្រងគ្រប់សកម្មភាព។',
    footerProduct: 'ផលិតផល',
    footerAccess: 'ការចូលប្រើ',
    footerInformation: 'ព័ត៌មាន',
    footerContact: 'ទំនាក់ទំនង',
    footerPrivacy: 'ឯកជនភាព',
    footerStatusLabel: 'ស្ថានភាព Prototype',
    footerStatus: 'ការផ្គូផ្គងលំនាំមានកំណែ · ត្រូវការការពិនិត្យដោយមនុស្ស',
    footerRights: '© 2026 KCMS',
  },
} as const

export type Locale = keyof typeof copy
