export const copy = {
  en: {
    howItWorks: 'How KCMS works', signIn: 'Sign in', language: 'ភាសាខ្មែរ',
    eyebrow: 'Khmer-first comment moderation',
    heading: 'Moderate Khmer comments with context—not guesswork.',
    description: 'Find harmful comments and scams faster. KCMS helps your team prioritize what needs attention, while humans decide every moderation action.',
    requestAccess: 'Request access', seeHow: 'See how it works',
    pathwayLabel: 'How a comment reaches human review', incoming: 'Facebook Page comment',
    sampleComment: 'គណនីនេះស្នើសុំលេខកូដ សូមប្រយ័ត្ន។', pattern: 'Automatic detection',
    patternDetail: 'Pattern matching · v0.1', review: 'Needs human review',
    reviewDetail: 'Possible scam signal', human: 'Your team decides',
    humanDetail: 'Leave · Hide · Unhide · Correct label', noAutomatic: 'Automatic detection · Human-approved Page actions',
    facebook: 'Facebook comments', languageSupport: 'Khmer + Khmerlish', humanControlled: 'Human controlled',
    overviewEyebrow: 'Service overview',
    overviewHeading: 'See one Facebook comment move through KCMS.',
    overviewDescription: 'A comment is detected automatically, reviewed by a person, and hidden or restored on the connected Page. This prototype walkthrough will be replaced by a recording of the verified live flow.',
    overviewDemoCta: 'Open the client workspace',
    overviewLoopLabel: 'Prototype walkthrough',
    overviewPause: 'Pause animation',
    overviewPlay: 'Play animation',
    overviewVideoUnsupported: 'Your browser cannot play this overview video.',
    overviewTranscriptLabel: 'Service overview transcript',
    overviewChapters: [
      'Comment posted on Facebook',
      'Automatic detection',
      'Human review',
      'Hide confirmed on Facebook',
      'Unhide restores the comment',
    ],
    workflowEyebrow: 'Three clear handoffs',
    workflowHeading: 'From Facebook comment to human decision.',
    workflowDescription: 'KCMS keeps the first version simple: connect a Page, surface comments that need attention, and let your team decide the action. No Meta developer workflow for client staff.',
    workflowSteps: [
      {
        title: 'Connect the Page',
        body: 'A Client links the Facebook Page once. KCMS keeps connection health visible so the team knows whether comments are still arriving.',
        meta: 'Setup',
      },
      {
        title: 'Prioritize review',
        body: 'Versioned pattern matching flags Khmer, Khmer slang, Khmerlish, scams, and harmful phrases while preserving ordinary complaints.',
        meta: 'Pattern matching v0.1',
      },
      {
        title: 'Decide with context',
        body: 'A trusted Client leaves, hides, unhides, or corrects the label. The action and the label stay separate for later learning.',
        meta: 'Human controlled',
      },
    ],
    navHumanControl: 'Human control',
    setTitle: 'Settings', setLead: 'Your workspace and your account.',
    setWorkspace: 'Workspace', setWorkspaceName: 'Workspace name',
    setWorkspaceOwnerOnly: 'Only an owner can rename the workspace.',
    setYou: 'You', setYourName: 'Your display name',
    setNameNote: 'Shown on the actions you take from now on. Past actions keep the name you used at the time.',
    setSave: 'Save', setSaved: 'Saved', setSaving: 'Saving…',
    setPlan: 'Workspace type', setSandbox: 'Demo workspace', setConnected: 'Approved',
    setSignOut: 'Sign out of KCMS',
    errNameRequired: 'Please enter a name.',
    teamTitle: 'Team', teamLead: 'People who can moderate this workspace.',
    teamYou: 'You', teamOwner: 'Owner', teamMember: 'Member',
    teamInvite: 'Create invitation link',
    teamInviteRole: 'Joins as',
    teamLinkTitle: 'Share this link',
    teamLinkBody: 'It works once and expires in 7 days. We cannot show it again, so copy it now.',
    teamCopy: 'Copy link', teamCopied: 'Copied',
    teamOpenInvites: 'Open invitations', teamRevoke: 'Revoke',
    teamExpires: 'Expires', teamRemove: 'Remove',
    teamLastOwner: 'A workspace must keep at least one owner. Make someone else an owner first.',
    teamOwnerOnly: 'Only an owner can invite or remove people.',
    joinTitle: 'Join', joinRole: 'You will join as',
    joinAccept: 'Join workspace', joinSignInFirst: 'Sign in to accept this invitation',
    joinInvalid: 'This invitation is invalid, expired, or already used.',
    joinDone: 'You have joined',
    connTitle: 'Connect a Facebook Page',
    connLead: 'KCMS is in a pilot. Connecting a real Page needs approval from our team first.',
    connPage: 'Facebook Page name or URL',
    connVolume: 'Comments per month',
    connTeam: 'People who will moderate',
    connNote: 'Anything we should know?', connNoteHint: 'Optional.',
    connSubmit: 'Request connection', connSending: 'Sending…',
    connPendingTitle: 'Request received',
    connPendingBody: 'We will review this and reply by email. You can keep using the demo workspace meanwhile.',
    connApprovedTitle: 'Approved',
    connApprovedBody: 'Your workspace can connect a Facebook Page. Meta authorization is not enabled yet, so we will contact you to finish setup.',
    connDeclinedTitle: 'Not approved',
    connResubmit: 'Submit another request',
    errPageName: 'Please enter the Page name or URL.',
    volUNDER_1K: 'Under 1,000', vol1K_TO_10K: '1,000 – 10,000',
    vol10K_TO_50K: '10,000 – 50,000', volOVER_50K: 'More than 50,000',
    teamJUST_ME: 'Just me', team2_TO_5: '2 – 5', team6_TO_20: '6 – 20', teamOVER_20: 'More than 20',
    adminTitle: 'Access requests', adminOps: 'Platform operations',
    adminPending: 'Pending', adminAll: 'All', adminEmpty: 'No requests right now.',
    adminApprove: 'Approve', adminDecline: 'Decline',
    adminReason: 'Reason for declining', adminReasonHint: 'The client sees this.',
    adminConfirmDecline: 'Confirm decline', adminCancel: 'Cancel',
    adminMonthly: 'comments/month', adminModerators: 'moderators',
    navAdmin: 'Administration',
    dashWorkspace: 'Client workspace',
    dashNavOverview: 'Overview',
    dashNavModerate: 'Moderate',
    dashNavPage: 'Page connection',
    dashNavTeam: 'Team',
    dashNavSettings: 'Settings',
    dashNotBuilt: 'Not in the prototype',
    dashPageStatus: 'Demo page',
    dashPageConnected: 'Sample data',
    dashOverviewTitle: 'Overview',
    dashOverviewSubtitle: 'What KCMS has done on this Page.',
    dashProcessed: 'Comments processed',
    dashNeedReview: 'Need review',
    dashReviewed: 'Reviewed',
    dashPending: 'Pending',
    dashBreakdown: 'Why comments surfaced',
    dashOutcomes: 'Moderation outcomes',
    dashNoOutcomes: 'No actions recorded yet.',
    dashLeft: 'Left visible', dashHidden: 'Hidden', dashUnhidden: 'Unhidden',
    dashOpenModerate: 'Review comments',
    openDemo: 'Open the demo',
    backHome: 'Back to home',
    requestTitle: 'Pilot access is by invitation',
    requestBody: 'KCMS is onboarding a small number of Cambodian organizations. Request access first; after review, KCMS sends a one-time link for creating your password.',
    requestDemoHint: 'Already approved? Use the sign-in page with the credentials you created from your invitation.',
    authSignInLead: 'Sign in to your moderation workspace.',
    authAccessPrompt: 'New to KCMS?',
    errName: 'Please enter your name.',
    errEmail: 'Please enter a valid email address.',
    errPasswordShort: 'Use at least 8 characters.',
    errPasswordRequired: 'Please enter your password.',
    errSummary: 'Please fix the following:',
    sandboxTitle: 'Demo workspace',
    sandboxBody: 'These are sample Khmer comments, not a live Facebook Page. Connecting a real Page needs approval while KCMS is in its pilot.',
    sandboxAdminBody: 'These are sample Khmer comments. This maintained test account can connect a Page to verify the live Meta workflow.',
    sandboxCta: 'Connect Facebook Page',
    authSignIn: 'Sign in',
    authEmail: 'Email', authPassword: 'Password',
    authSignInTitle: 'Sign in to KCMS',
    authTelegram: 'Continue with Telegram',
    authOr: 'or',
    authWorking: 'Please wait…',
    authFailed: 'Email or password is incorrect.',
    authUnreachable: 'Could not reach KCMS. Please try again.',
    authSignOut: 'Sign out',
    authSignedInAs: 'Signed in as',
    signInTitle: 'Sign-in is not enabled yet',
    signInBody: 'The prototype does not have accounts. The moderation workspace is open so you can see how KCMS routes Khmer comments.',
    notFoundTitle: 'This page does not exist yet',
    notFoundBody: 'KCMS is an early prototype. Only the public site and the moderation workspace are built.',
    colComment: 'Comment', colSeverity: 'Severity', colTarget: 'Target',
    colReason: 'Why surfaced', colStatus: 'Status', colActions: 'Actions',
    statusPending: 'Pending', statusDone: 'Actioned',
    pagePrev: 'Previous', pageNext: 'Next',
    pageOf: 'of', pageShowing: 'Showing',
    rowExpand: 'Open', rowCollapse: 'Close',
    modTitle: 'Moderate',
    modSubtitle: 'Comments KCMS surfaced for your team.',
    modBackToSite: 'Back to site',
    modLoading: 'Loading comments…',
    modWaking: 'Waking the service — the free plan sleeps when idle. This can take up to a minute.',
    modErrorTitle: 'Could not reach KCMS',
    modErrorBody: 'The moderation service did not respond. Nothing has been changed.',
    modRetry: 'Try again',
    modEmpty: 'Nothing needs review right now.',
    modWhySurfaced: 'Why this surfaced',
    modConfidence: 'Confidence',
    modCorrect: 'Correct the label',
    modCorrectCancel: 'Cancel',
    modCorrectSave: 'Save correction',
    modCorrectHint: 'This records what the label should be. It does not hide or unhide the comment.',
    modCorrectSeverity: 'Severity',
    modCorrectTarget: 'Target',
    modCorrected: 'Corrected to',
    modLeave: 'Leave visible',
    modHide: 'Hide',
    modUnhide: 'Unhide',
    modActioned: 'Last action',
    modBy: 'by',
    modReasons: {
      triage: 'Possible harm — review first',
      institution_sample: 'Aimed at an organization — never hidden automatically',
      novel_language: 'Unfamiliar wording — KCMS did not recognise this',
      uncertainty: 'Low confidence — a human decides',
      cleared: 'No risk pattern matched',
    },
    modSeverity: { SAFE: 'Safe', OFFENSIVE: 'Offensive', HARMFUL: 'Harmful' },
    modTarget: { PERSON: 'Person', INSTITUTION: 'Institution', NEITHER: 'No clear target' },
    modAbstain: 'Abstained',
    modCounts: 'comments',
    khmerEyebrow: 'Built for Khmer',
    khmerHeading: 'Khmer, Khmerlish, and the slang in between.',
    khmerDescription: 'Most moderation tools read Khmer as noise. KCMS matches Khmer script, romanized Khmerlish, everyday slang, misspellings, and deliberately obfuscated words — then separates who the comment is aimed at.',
    khmerCoverageLabel: 'Pattern matching covers',
    khmerCoverage: ['Khmer script', 'Khmerlish and code-switching', 'Everyday slang', 'Misspellings and obfuscated words'],
    khmerExamplesLabel: 'Same frustration, different target',
    khmerExamples: [
      {
        comment: 'សេវាកម្មក្រុមហ៊ុននេះយឺតណាស់ ខកចិត្តខ្លាំង។',
        gloss: '“This company’s service is so slow. Very disappointed.”',
        target: 'Institution',
        outcome: 'Stays visible',
        note: 'Criticism of an organization is protected. KCMS never removes it automatically.',
        tone: 'safe',
      },
      {
        comment: 'អ្នកនេះល្ងង់ណាស់ កុំឱ្យវានិយាយ។',
        gloss: '“This person is so stupid. Don’t let them speak.”',
        target: 'Person',
        outcome: 'Needs review',
        note: 'Person-directed abuse is surfaced so your team can decide what happens.',
        tone: 'review',
      },
    ],
    controlEyebrow: 'Human control',
    controlHeading: 'You decide what KCMS is allowed to do.',
    controlDescription: 'Detection runs automatically on every comment. What happens next is your team’s decision — and some limits stay in place no matter what you switch on.',
    controlGuarantees: [
      'Automatic hiding is off today. Every hide and unhide is performed by a person on your team.',
      'Actions are reversible, and the record shows who did what.',
      'Correcting a model label is separate from hiding a comment.',
      'Criticism aimed at an organization is never hidden automatically — at any confidence, under any setting.',
      'The model is frozen between releases. Your corrections feed the next training round, reviewed offline — never live.',
    ],
    controlScopeLabel: 'Current scope',
    controlScope: 'Facebook Page comments only. Messenger and Instagram are not connected yet.',
    accessEyebrow: 'Early access',
    accessHeading: 'Start a pilot with your Page and your team.',
    accessDescription: 'KCMS is onboarding a small number of Cambodian organizations. We review each pilot around its connected Facebook Pages and moderation workflow.',
    planName: 'Pilot access',
    planBadge: 'Now onboarding',
    planPrice: 'Pricing discussed with your team',
    planFeaturesLabel: 'What a pilot includes',
    planFeatures: [
      'Facebook Page comment moderation',
      'Khmer and Khmerlish pattern matching',
      'Human review workflow',
      'Team access and roles',
      'Basic performance summary',
      'Setup and connection support',
    ],
    planCta: 'Request pilot access',
    planNote: 'Future pricing may depend on the number of connected Facebook Pages.',
    faqEyebrow: 'FAQ',
    faqHeading: 'Questions before connecting a Page.',
    faqDescription: 'Clear answers about automation, Facebook access, learning, and the current pilot.',
    faqItems: [
      {
        question: 'Does KCMS automatically detect comments?',
        answer: 'Yes. Detection and prioritization are automatic. Pattern matching powers the current prototype; a trained Khmer model will replace it after offline training and evaluation.',
      },
      {
        question: 'Does KCMS automatically hide or delete comments?',
        answer: 'Automatic hiding is currently off. A moderator decides whether to leave, hide, or unhide each surfaced comment.',
      },
      {
        question: 'What languages does KCMS support?',
        answer: 'KCMS focuses on Khmer, Khmerlish, everyday slang, misspellings, code-switching, and deliberately obfuscated wording.',
      },
      {
        question: 'Do I need Facebook Developer knowledge?',
        answer: 'No. Clients connect an authorized Page through KCMS, while the platform handles the technical integration.',
      },
      {
        question: 'How do corrections improve KCMS?',
        answer: 'Explicit corrections become candidates for a reviewed future training round. They never retrain or change the live system automatically.',
      },
      {
        question: 'Does KCMS use every client comment for training?',
        answer: 'No. Customer comments remain operational data by default. Dataset use requires permission, explicit labels, curation, and privacy review.',
      },
      {
        question: 'Does KCMS support Messenger or Instagram?',
        answer: 'Not currently. The initial product focuses on Facebook Page comments.',
      },
      {
        question: 'How much does KCMS cost?',
        answer: 'KCMS is currently onboarding pilot organizations. Future pricing may depend on the number of connected Facebook Pages. Contact us to discuss pilot access.',
      },
    ],
    footerNavLabel: 'Footer navigation',
    footerTagline: 'Khmer-first Facebook comment moderation, with humans in control of every action.',
    footerProduct: 'Product',
    footerAccess: 'Access',
    footerInformation: 'Information',
    footerContact: 'Contact',
    footerPrivacy: 'Privacy',
    footerStatusLabel: 'Prototype status',
    footerStatus: 'Versioned pattern matching · Human review required',
    footerRights: '© 2026 KCMS',
  },
  km: {
    howItWorks: 'របៀបដំណើរការ', signIn: 'ចូលប្រើ', language: 'English',
    eyebrow: 'ការគ្រប់គ្រងមតិយោបល់ខ្មែរជាចម្បង',
    heading: 'គ្រប់គ្រងមតិយោបល់ខ្មែរ ដោយយល់ពីបរិបទ មិនមែនការស្មាន។',
    description: 'ស្វែងរកមតិយោបល់បង្កគ្រោះថ្នាក់ និងការបោកប្រាស់បានលឿនជាងមុន។ KCMS ជួយក្រុមរបស់អ្នកកំណត់អាទិភាព ខណៈមនុស្សជាអ្នកសម្រេចចិត្តលើសកម្មភាពគ្រប់យ៉ាង។',
    requestAccess: 'ស្នើសុំប្រើប្រាស់', seeHow: 'មើលរបៀបដំណើរការ',
    pathwayLabel: 'របៀបដែលមតិយោបល់ទៅដល់ការពិនិត្យដោយមនុស្ស', incoming: 'មតិយោបល់លើទំព័រ Facebook',
    sampleComment: 'គណនីនេះស្នើសុំលេខកូដ សូមប្រយ័ត្ន។', pattern: 'ការរកឃើញស្វ័យប្រវត្តិ',
    patternDetail: 'ការផ្គូផ្គងលំនាំ · v0.1', review: 'ត្រូវការមនុស្សពិនិត្យ',
    reviewDetail: 'អាចជាសញ្ញាបោកប្រាស់', human: 'ក្រុមរបស់អ្នកជាអ្នកសម្រេច',
    humanDetail: 'ទុក · លាក់ · បើកលាក់វិញ · កែស្លាក', noAutomatic: 'រកឃើញស្វ័យប្រវត្តិ · មនុស្សអនុម័តសកម្មភាពលើទំព័រ',
    facebook: 'មតិយោបល់ Facebook', languageSupport: 'ខ្មែរ + Khmerlish', humanControlled: 'គ្រប់គ្រងដោយមនុស្ស',
    overviewEyebrow: 'ទិដ្ឋភាពទូទៅនៃសេវាកម្ម',
    overviewHeading: 'មើលមតិយោបល់ Facebook មួយឆ្លងកាត់ KCMS។',
    overviewDescription: 'មតិយោបល់ត្រូវបានរកឃើញដោយស្វ័យប្រវត្តិ ពិនិត្យដោយមនុស្ស ហើយលាក់ ឬបើកលាក់វិញលើទំព័រដែលបានភ្ជាប់។ ការបង្ហាញគំរូនេះនឹងត្រូវជំនួសដោយវីដេអូនៃដំណើរការពិតដែលបានផ្ទៀងផ្ទាត់។',
    overviewDemoCta: 'បើកកន្លែងធ្វើការរបស់អតិថិជន',
    overviewLoopLabel: 'ការបង្ហាញគំរូ',
    overviewPause: 'ផ្អាកចលនា',
    overviewPlay: 'ចាប់ផ្តើមចលនា',
    overviewVideoUnsupported: 'កម្មវិធីរុករករបស់អ្នកមិនអាចចាក់វីដេអូនេះបានទេ។',
    overviewTranscriptLabel: 'សេចក្ដីសង្ខេបនៃទិដ្ឋភាពសេវាកម្ម',
    overviewChapters: [
      'មតិយោបល់បានបង្ហោះលើ Facebook',
      'ការរកឃើញស្វ័យប្រវត្តិ',
      'ការពិនិត្យដោយមនុស្ស',
      'Facebook បានបញ្ជាក់ការលាក់',
      'បើកលាក់វិញ ដើម្បីស្តារមតិយោបល់',
    ],
    workflowEyebrow: 'ជំហានច្បាស់ ៣',
    workflowHeading: 'ពីមតិយោបល់ Facebook ទៅការសម្រេចដោយមនុស្ស។',
    workflowDescription: 'KCMS រក្សាជំនាន់ដំបូងឱ្យសាមញ្ញ៖ ភ្ជាប់ទំព័រ បង្ហាញមតិយោបល់ដែលត្រូវការយកចិត្តទុកដាក់ ហើយឱ្យក្រុមរបស់អ្នកសម្រេចសកម្មភាព។ បុគ្គលិកអតិថិជនមិនចាំបាច់ប្រើ Facebook Developer ដោយផ្ទាល់។',
    workflowSteps: [
      {
        title: 'ភ្ជាប់ទំព័រ',
        body: 'Client ភ្ជាប់ Facebook Page ម្តង។ KCMS បង្ហាញស្ថានភាពភ្ជាប់ ដើម្បីឱ្យក្រុមដឹងថាមតិយោបល់នៅតែចូលមកឬអត់។',
        meta: 'ការរៀបចំ',
      },
      {
        title: 'កំណត់អាទិភាពពិនិត្យ',
        body: 'ការផ្គូផ្គងលំនាំមានកំណែ ជួយចាប់សញ្ញាខ្មែរ ពាក្យស្លែង Khmerlish ការបោកប្រាស់ និងពាក្យបង្កគ្រោះថ្នាក់ ខណៈរក្សាការរិះគន់ធម្មតា។',
        meta: 'Pattern matching v0.1',
      },
      {
        title: 'សម្រេចដោយមានបរិបទ',
        body: 'Client ដែលទុកចិត្តអាចទុក លាក់ បើកលាក់វិញ ឬកែស្លាក។ សកម្មភាព និងស្លាកត្រូវបានរក្សាផ្សេងគ្នាសម្រាប់ការរៀនពេលក្រោយ។',
        meta: 'គ្រប់គ្រងដោយមនុស្ស',
      },
    ],
    navHumanControl: 'ការគ្រប់គ្រងដោយមនុស្ស',
    setTitle: 'ការកំណត់', setLead: 'កន្លែងធ្វើការ និងគណនីរបស់អ្នក។',
    setWorkspace: 'កន្លែងធ្វើការ', setWorkspaceName: 'ឈ្មោះកន្លែងធ្វើការ',
    setWorkspaceOwnerOnly: 'មានតែម្ចាស់ទេដែលអាចប្តូរឈ្មោះកន្លែងធ្វើការ។',
    setYou: 'អ្នក', setYourName: 'ឈ្មោះបង្ហាញរបស់អ្នក',
    setNameNote: 'បង្ហាញលើសកម្មភាពដែលអ្នកធ្វើចាប់ពីពេលនេះ។ សកម្មភាពពីមុនរក្សាឈ្មោះដែលអ្នកប្រើពេលនោះ។',
    setSave: 'រក្សាទុក', setSaved: 'បានរក្សាទុក', setSaving: 'កំពុងរក្សាទុក…',
    setPlan: 'ប្រភេទកន្លែងធ្វើការ', setSandbox: 'កន្លែងសាកល្បង', setConnected: 'បានអនុម័ត',
    setSignOut: 'ចាកចេញពី KCMS',
    errNameRequired: 'សូមបញ្ចូលឈ្មោះ។',
    teamTitle: 'ក្រុម', teamLead: 'អ្នកដែលអាចពិនិត្យក្នុងកន្លែងធ្វើការនេះ។',
    teamYou: 'អ្នក', teamOwner: 'ម្ចាស់', teamMember: 'សមាជិក',
    teamInvite: 'បង្កើតតំណអញ្ជើញ',
    teamInviteRole: 'ចូលរួមជា',
    teamLinkTitle: 'ចែករំលែកតំណនេះ',
    teamLinkBody: 'វាដំណើរការតែម្តង ហើយផុតកំណត់ក្នុង ៧ ថ្ងៃ។ យើងមិនអាចបង្ហាញវាម្តងទៀតទេ សូមចម្លងឥឡូវនេះ។',
    teamCopy: 'ចម្លងតំណ', teamCopied: 'បានចម្លង',
    teamOpenInvites: 'តំណអញ្ជើញដែលនៅសល់', teamRevoke: 'ដកហូត',
    teamExpires: 'ផុតកំណត់', teamRemove: 'ដកចេញ',
    teamLastOwner: 'កន្លែងធ្វើការត្រូវមានម្ចាស់យ៉ាងតិចម្នាក់។ សូមតែងតាំងម្ចាស់ថ្មីជាមុនសិន។',
    teamOwnerOnly: 'មានតែម្ចាស់ទេដែលអាចអញ្ជើញ ឬដកចេញបាន។',
    joinTitle: 'ចូលរួម', joinRole: 'អ្នកនឹងចូលរួមជា',
    joinAccept: 'ចូលរួមកន្លែងធ្វើការ', joinSignInFirst: 'សូមចូលប្រើដើម្បីទទួលយកការអញ្ជើញនេះ',
    joinInvalid: 'ការអញ្ជើញនេះមិនត្រឹមត្រូវ ផុតកំណត់ ឬបានប្រើរួចហើយ។',
    joinDone: 'អ្នកបានចូលរួម',
    connTitle: 'ភ្ជាប់ទំព័រ Facebook',
    connLead: 'KCMS នៅដំណាក់កាលសាកល្បង។ ការភ្ជាប់ទំព័រពិតត្រូវការការអនុម័តពីក្រុមយើងជាមុនសិន។',
    connPage: 'ឈ្មោះ ឬតំណទំព័រ Facebook',
    connVolume: 'មតិយោបល់ក្នុងមួយខែ',
    connTeam: 'អ្នកដែលនឹងពិនិត្យ',
    connNote: 'មានអ្វីដែលយើងគួរដឹងទេ?', connNoteHint: 'ជាជម្រើស។',
    connSubmit: 'ស្នើសុំភ្ជាប់', connSending: 'កំពុងផ្ញើ…',
    connPendingTitle: 'បានទទួលសំណើ',
    connPendingBody: 'យើងនឹងពិនិត្យ ហើយឆ្លើយតបតាមអ៊ីមែល។ អ្នកអាចបន្តប្រើកន្លែងសាកល្បងបាន។',
    connApprovedTitle: 'បានអនុម័ត',
    connApprovedBody: 'កន្លែងធ្វើការរបស់អ្នកអាចភ្ជាប់ទំព័រ Facebook បាន។ ការអនុញ្ញាតពី Meta មិនទាន់បើកទេ ដូច្នេះយើងនឹងទាក់ទងអ្នកដើម្បីបញ្ចប់ការរៀបចំ។',
    connDeclinedTitle: 'មិនបានអនុម័ត',
    connResubmit: 'ដាក់សំណើម្តងទៀត',
    errPageName: 'សូមបញ្ចូលឈ្មោះ ឬតំណទំព័រ។',
    volUNDER_1K: 'តិចជាង ១,០០០', vol1K_TO_10K: '១,០០០ – ១០,០០០',
    vol10K_TO_50K: '១០,០០០ – ៥០,០០០', volOVER_50K: 'ច្រើនជាង ៥០,០០០',
    teamJUST_ME: 'តែខ្ញុំ', team2_TO_5: '២ – ៥', team6_TO_20: '៦ – ២០', teamOVER_20: 'ច្រើនជាង ២០',
    adminTitle: 'សំណើចូលប្រើ', adminOps: 'ប្រតិបត្តិការវេទិកា',
    adminPending: 'រង់ចាំ', adminAll: 'ទាំងអស់', adminEmpty: 'គ្មានសំណើនៅពេលនេះទេ។',
    adminApprove: 'អនុម័ត', adminDecline: 'បដិសេធ',
    adminReason: 'មូលហេតុនៃការបដិសេធ', adminReasonHint: 'អតិថិជននឹងឃើញអត្ថបទនេះ។',
    adminConfirmDecline: 'បញ្ជាក់ការបដិសេធ', adminCancel: 'បោះបង់',
    adminMonthly: 'មតិយោបល់/ខែ', adminModerators: 'អ្នកពិនិត្យ',
    navAdmin: 'ការគ្រប់គ្រងវេទិកា',
    dashWorkspace: 'កន្លែងធ្វើការអតិថិជន',
    dashNavOverview: 'ទិដ្ឋភាពរួម',
    dashNavModerate: 'ពិនិត្យ',
    dashNavPage: 'ការភ្ជាប់ទំព័រ',
    dashNavTeam: 'ក្រុម',
    dashNavSettings: 'ការកំណត់',
    dashNotBuilt: 'មិនមានក្នុងគំរូ',
    dashPageStatus: 'ទំព័រសាកល្បង',
    dashPageConnected: 'ទិន្នន័យគំរូ',
    dashOverviewTitle: 'ទិដ្ឋភាពរួម',
    dashOverviewSubtitle: 'អ្វីដែល KCMS បានធ្វើលើទំព័រនេះ។',
    dashProcessed: 'មតិយោបល់បានដំណើរការ',
    dashNeedReview: 'ត្រូវការពិនិត្យ',
    dashReviewed: 'បានពិនិត្យ',
    dashPending: 'កំពុងរង់ចាំ',
    dashBreakdown: 'ហេតុអ្វីមតិយោបល់បានបង្ហាញ',
    dashOutcomes: 'លទ្ធផលនៃការគ្រប់គ្រង',
    dashNoOutcomes: 'មិនទាន់មានសកម្មភាពត្រូវបានកត់ត្រាទេ។',
    dashLeft: 'ទុកឱ្យបង្ហាញ', dashHidden: 'បានលាក់', dashUnhidden: 'បានបើកលាក់វិញ',
    dashOpenModerate: 'ពិនិត្យមតិយោបល់',
    openDemo: 'បើកការសាកល្បង',
    backHome: 'ត្រឡប់ទៅទំព័រដើម',
    requestTitle: 'ការចូលរួមសាកល្បងតាមការអញ្ជើញ',
    requestBody: 'KCMS កំពុងទទួលអង្គការកម្ពុជាមួយចំនួនតូច។ សូមស្នើសុំចូលប្រើជាមុន។ បន្ទាប់ពីពិនិត្យ KCMS នឹងផ្ញើតំណប្រើម្តង ដើម្បីបង្កើតពាក្យសម្ងាត់។',
    requestDemoHint: 'បានអនុម័តរួចហើយ? សូមចូលប្រើដោយព័ត៌មានដែលអ្នកបានបង្កើតតាមតំណអញ្ជើញ។',
    authSignInLead: 'ចូលទៅកន្លែងធ្វើការពិនិត្យរបស់អ្នក។',
    authAccessPrompt: 'មិនទាន់មានគណនី KCMS?',
    errName: 'សូមបញ្ចូលឈ្មោះរបស់អ្នក។',
    errEmail: 'សូមបញ្ចូលអាសយដ្ឋានអ៊ីមែលត្រឹមត្រូវ។',
    errPasswordShort: 'ប្រើយ៉ាងតិច ៨ តួអក្សរ។',
    errPasswordRequired: 'សូមបញ្ចូលពាក្យសម្ងាត់របស់អ្នក។',
    errSummary: 'សូមកែខាងក្រោម៖',
    sandboxTitle: 'កន្លែងធ្វើការសាកល្បង',
    sandboxBody: 'ទាំងនេះជាមតិយោបល់ខ្មែរគំរូ មិនមែនទំព័រ Facebook ពិតទេ។ ការភ្ជាប់ទំព័រពិតត្រូវការការអនុម័ត ខណៈ KCMS នៅដំណាក់កាលសាកល្បង។',
    sandboxAdminBody: 'ទាំងនេះជាមតិយោបល់ខ្មែរគំរូ។ គណនីសាកល្បងរបស់ក្រុម KCMS អាចភ្ជាប់ Page ដើម្បីផ្ទៀងផ្ទាត់ដំណើរការ Meta ពិត។',
    sandboxCta: 'ភ្ជាប់ Facebook Page',
    authSignIn: 'ចូលប្រើ',
    authEmail: 'អ៊ីមែល', authPassword: 'ពាក្យសម្ងាត់',
    authSignInTitle: 'ចូលប្រើ KCMS',
    authTelegram: 'បន្តជាមួយ Telegram',
    authOr: 'ឬ',
    authWorking: 'សូមរង់ចាំ…',
    authFailed: 'អ៊ីមែល ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ។',
    authUnreachable: 'មិនអាចភ្ជាប់ទៅ KCMS។ សូមព្យាយាមម្តងទៀត។',
    authSignOut: 'ចាកចេញ',
    authSignedInAs: 'ចូលប្រើជា',
    signInTitle: 'ការចូលប្រើមិនទាន់បើកនៅឡើយ',
    signInBody: 'គំរូនេះមិនទាន់មានគណនីទេ។ កន្លែងពិនិត្យមតិយោបល់បើកចំហ ដើម្បីឱ្យអ្នកឃើញរបៀបដែល KCMS បញ្ជូនមតិយោបល់ខ្មែរ។',
    notFoundTitle: 'ទំព័រនេះមិនទាន់មានទេ',
    notFoundBody: 'KCMS ជាគំរូដំបូង។ មានតែគេហទំព័រសាធារណៈ និងកន្លែងពិនិត្យមតិយោបល់ប៉ុណ្ណោះដែលបានសាង។',
    colComment: 'មតិយោបល់', colSeverity: 'កម្រិត', colTarget: 'គោលដៅ',
    colReason: 'ហេតុផល', colStatus: 'ស្ថានភាព', colActions: 'សកម្មភាព',
    statusPending: 'រង់ចាំ', statusDone: 'បានធ្វើ',
    pagePrev: 'មុន', pageNext: 'បន្ទាប់',
    pageOf: 'នៃ', pageShowing: 'បង្ហាញ',
    rowExpand: 'បើក', rowCollapse: 'បិទ',
    modTitle: 'ពិនិត្យមតិយោបល់',
    modSubtitle: 'មតិយោបល់ដែល KCMS បង្ហាញសម្រាប់ក្រុមរបស់អ្នក។',
    modBackToSite: 'ត្រឡប់ទៅគេហទំព័រ',
    modLoading: 'កំពុងទាញមតិយោបល់…',
    modWaking: 'កំពុងដាស់សេវាកម្ម — គម្រោងឥតគិតថ្លៃដេកនៅពេលទំនេរ។ អាចចំណាយពេលដល់មួយនាទី។',
    modErrorTitle: 'មិនអាចភ្ជាប់ទៅ KCMS',
    modErrorBody: 'សេវាកម្មពិនិត្យមិនបានឆ្លើយតប។ គ្មានអ្វីត្រូវបានផ្លាស់ប្តូរឡើយ។',
    modRetry: 'ព្យាយាមម្តងទៀត',
    modEmpty: 'គ្មានអ្វីត្រូវពិនិត្យនៅពេលនេះទេ។',
    modWhySurfaced: 'ហេតុអ្វីបានបង្ហាញ',
    modConfidence: 'កម្រិតជឿជាក់',
    modCorrect: 'កែស្លាក',
    modCorrectCancel: 'បោះបង់',
    modCorrectSave: 'រក្សាទុកការកែ',
    modCorrectHint: 'នេះកត់ត្រាថាស្លាកគួរជាអ្វី។ វាមិនលាក់ ឬបើកលាក់មតិយោបល់ឡើយ។',
    modCorrectSeverity: 'កម្រិតធ្ងន់ធ្ងរ',
    modCorrectTarget: 'គោលដៅ',
    modCorrected: 'បានកែទៅជា',
    modLeave: 'ទុកឱ្យបង្ហាញ',
    modHide: 'លាក់',
    modUnhide: 'បើកលាក់វិញ',
    modActioned: 'សកម្មភាពចុងក្រោយ',
    modBy: 'ដោយ',
    modReasons: {
      triage: 'អាចមានគ្រោះថ្នាក់ — ពិនិត្យមុន',
      institution_sample: 'សំដៅលើអង្គភាព — មិនលាក់ស្វ័យប្រវត្តិឡើយ',
      novel_language: 'ពាក្យមិនធ្លាប់ស្គាល់ — KCMS មិនអាចអានបាន',
      uncertainty: 'កម្រិតជឿជាក់ទាប — មនុស្សសម្រេច',
      cleared: 'គ្មានលំនាំហានិភ័យត្រូវគ្នា',
    },
    modSeverity: { SAFE: 'សុវត្ថិភាព', OFFENSIVE: 'ប្រមាថ', HARMFUL: 'បង្កគ្រោះថ្នាក់' },
    modTarget: { PERSON: 'បុគ្គល', INSTITUTION: 'អង្គភាព', NEITHER: 'គ្មានគោលដៅច្បាស់' },
    modAbstain: 'មិនសម្រេច',
    modCounts: 'មតិយោបល់',
    khmerEyebrow: 'សាងសម្រាប់ភាសាខ្មែរ',
    khmerHeading: 'ខ្មែរ Khmerlish និងពាក្យស្លែងនៅចន្លោះ។',
    khmerDescription: 'ឧបករណ៍គ្រប់គ្រងភាគច្រើនអានភាសាខ្មែរជាសំឡេងរំខាន។ KCMS ផ្គូផ្គងអក្សរខ្មែរ Khmerlish ពាក្យស្លែងប្រចាំថ្ងៃ ពាក្យសរសេរខុស និងពាក្យបំបាំង រួចបែងចែកថាមតិយោបល់នោះសំដៅលើនរណា។',
    khmerCoverageLabel: 'ការផ្គូផ្គងលំនាំគ្របដណ្តប់',
    khmerCoverage: ['អក្សរខ្មែរ', 'Khmerlish និងការលាយភាសា', 'ពាក្យស្លែងប្រចាំថ្ងៃ', 'ពាក្យសរសេរខុស និងពាក្យបំបាំង'],
    khmerExamplesLabel: 'ការខកចិត្តដូចគ្នា គោលដៅខុសគ្នា',
    khmerExamples: [
      {
        comment: 'សេវាកម្មក្រុមហ៊ុននេះយឺតណាស់ ខកចិត្តខ្លាំង។',
        gloss: '“សេវាកម្មរបស់ក្រុមហ៊ុននេះយឺតណាស់។ ខកចិត្តខ្លាំង។”',
        target: 'អង្គភាព',
        outcome: 'នៅតែបង្ហាញ',
        note: 'ការរិះគន់អង្គភាពត្រូវបានការពារ។ KCMS មិនលុបវាដោយស្វ័យប្រវត្តិឡើយ។',
        tone: 'safe',
      },
      {
        comment: 'អ្នកនេះល្ងង់ណាស់ កុំឱ្យវានិយាយ។',
        gloss: '“អ្នកនេះល្ងង់ណាស់។ កុំឱ្យគាត់និយាយ។”',
        target: 'បុគ្គល',
        outcome: 'ត្រូវការពិនិត្យ',
        note: 'ការវាយប្រហារសំដៅលើបុគ្គល ត្រូវបានបង្ហាញដល់ក្រុមរបស់អ្នកដើម្បីសម្រេច។',
        tone: 'review',
      },
    ],
    controlEyebrow: 'ការគ្រប់គ្រងដោយមនុស្ស',
    controlHeading: 'អ្នកជាអ្នកសម្រេចថា KCMS អាចធ្វើអ្វីបាន។',
    controlDescription: 'ការរកឃើញដំណើរការស្វ័យប្រវត្តិលើមតិយោបល់គ្រប់មួយ។ អ្វីដែលកើតឡើងបន្ទាប់ គឺជាការសម្រេចរបស់ក្រុមអ្នក ហើយដែនកំណត់មួយចំនួននៅតែមាន ទោះបីអ្នកបើកមុខងារណាក៏ដោយ។',
    controlGuarantees: [
      'ការលាក់ស្វ័យប្រវត្តិត្រូវបានបិទនៅពេលនេះ។ រាល់ការលាក់ និងការបើកលាក់វិញ ធ្វើឡើងដោយមនុស្សក្នុងក្រុមរបស់អ្នក។',
      'សកម្មភាពអាចត្រឡប់វិញបាន ហើយកំណត់ត្រាបង្ហាញថានរណាធ្វើអ្វី។',
      'ការកែស្លាកគំរូ ដាច់ដោយឡែកពីការលាក់មតិយោបល់។',
      'ការរិះគន់ដែលសំដៅលើអង្គភាព មិនត្រូវបានលាក់ដោយស្វ័យប្រវត្តិឡើយ ទោះកម្រិតជឿជាក់ណា ឬការកំណត់បែបណាក៏ដោយ។',
      'គំរូត្រូវបានបង្កកចន្លោះការចេញផ្សាយនីមួយៗ។ ការកែតម្រូវរបស់អ្នកចូលទៅក្នុងវគ្គហ្វឹកហាត់បន្ទាប់ ដែលពិនិត្យក្រៅប្រព័ន្ធ មិនមែនផ្ទាល់ឡើយ។',
    ],
    controlScopeLabel: 'វិសាលភាពបច្ចុប្បន្ន',
    controlScope: 'មតិយោបល់លើទំព័រ Facebook តែប៉ុណ្ណោះ។ Messenger និង Instagram មិនទាន់ភ្ជាប់នៅឡើយទេ។',
    accessEyebrow: 'ការចូលប្រើដំបូង',
    accessHeading: 'ចាប់ផ្តើមសាកល្បងជាមួយទំព័រ និងក្រុមរបស់អ្នក។',
    accessDescription: 'KCMS កំពុងទទួលអង្គការកម្ពុជាមួយចំនួនតូច។ យើងពិនិត្យការសាកល្បងតាម Facebook Page ដែលត្រូវភ្ជាប់ និងដំណើរការគ្រប់គ្រងមតិយោបល់។',
    planName: 'ការចូលប្រើសាកល្បង',
    planBadge: 'កំពុងទទួល',
    planPrice: 'តម្លៃពិភាក្សាជាមួយក្រុមរបស់អ្នក',
    planFeaturesLabel: 'អ្វីដែលមានក្នុងការសាកល្បង',
    planFeatures: [
      'ការគ្រប់គ្រងមតិយោបល់លើទំព័រ Facebook',
      'ការផ្គូផ្គងលំនាំខ្មែរ និង Khmerlish',
      'ដំណើរការពិនិត្យដោយមនុស្ស',
      'ការចូលប្រើ និងតួនាទីសម្រាប់ក្រុម',
      'សេចក្តីសង្ខេបការអនុវត្តជាមូលដ្ឋាន',
      'ជំនួយក្នុងការរៀបចំ និងការភ្ជាប់',
    ],
    planCta: 'ស្នើសុំការចូលប្រើសាកល្បង',
    planNote: 'តម្លៃនាពេលអនាគតអាចអាស្រ័យលើចំនួន Facebook Page ដែលបានភ្ជាប់។',
    faqEyebrow: 'សំណួរញឹកញាប់',
    faqHeading: 'សំណួរមុនពេលភ្ជាប់ទំព័រ។',
    faqDescription: 'ចម្លើយច្បាស់លាស់អំពីស្វ័យប្រវត្តិកម្ម ការចូលប្រើ Facebook ការរៀនរបស់ប្រព័ន្ធ និងការសាកល្បងបច្ចុប្បន្ន។',
    faqItems: [
      {
        question: 'តើ KCMS រកឃើញមតិយោបល់ដោយស្វ័យប្រវត្តិទេ?',
        answer: 'បាទ/ចាស។ ការរកឃើញ និងការកំណត់អាទិភាពដំណើរការដោយស្វ័យប្រវត្តិ។ Prototype បច្ចុប្បន្នប្រើការផ្គូផ្គងលំនាំ ហើយគំរូភាសាខ្មែរដែលបានបណ្តុះបណ្តាលនឹងជំនួសវាបន្ទាប់ពីការបណ្តុះបណ្តាល និងវាយតម្លៃក្រៅប្រព័ន្ធ។',
      },
      {
        question: 'តើ KCMS លាក់ ឬលុបមតិយោបល់ដោយស្វ័យប្រវត្តិទេ?',
        answer: 'ការលាក់ដោយស្វ័យប្រវត្តិត្រូវបានបិទនៅពេលនេះ។ អ្នកគ្រប់គ្រងជាអ្នកសម្រេចថាត្រូវទុក លាក់ ឬបើកលាក់មតិយោបល់នីមួយៗវិញ។',
      },
      {
        question: 'តើ KCMS គាំទ្រភាសាអ្វីខ្លះ?',
        answer: 'KCMS ផ្តោតលើភាសាខ្មែរ Khmerlish ពាក្យស្លែង ការសរសេរខុស ការលាយភាសា និងពាក្យដែលត្រូវបានកែប្រែដើម្បីគេចពីការរកឃើញ។',
      },
      {
        question: 'តើខ្ញុំត្រូវចេះ Facebook Developer ទេ?',
        answer: 'មិនចាំបាច់ទេ។ អតិថិជនភ្ជាប់ទំព័រដែលមានសិទ្ធិតាម KCMS ហើយ Platform ជាអ្នកគ្រប់គ្រងការភ្ជាប់បច្ចេកទេស។',
      },
      {
        question: 'តើការកែស្លាកជួយកែលម្អ KCMS ដូចម្តេច?',
        answer: 'ការកែស្លាកច្បាស់លាស់អាចក្លាយជាទិន្នន័យសម្រាប់វគ្គបណ្តុះបណ្តាលបន្ទាប់ បន្ទាប់ពីការពិនិត្យ។ វាមិនបណ្តុះបណ្តាល ឬប្តូរប្រព័ន្ធដែលកំពុងដំណើរការដោយស្វ័យប្រវត្តិទេ។',
      },
      {
        question: 'តើ KCMS ប្រើមតិយោបល់អតិថិជនទាំងអស់សម្រាប់បណ្តុះបណ្តាលទេ?',
        answer: 'ទេ។ មតិយោបល់អតិថិជនជាទិន្នន័យប្រតិបត្តិការតាមលំនាំដើម។ ការប្រើសម្រាប់ Dataset ត្រូវការការអនុញ្ញាត ស្លាកច្បាស់លាស់ ការជ្រើសរើស និងការពិនិត្យឯកជនភាព។',
      },
      {
        question: 'តើ KCMS គាំទ្រ Messenger ឬ Instagram ទេ?',
        answer: 'មិនទាន់ទេ។ ផលិតផលដំបូងផ្តោតលើមតិយោបល់ Facebook Page។',
      },
      {
        question: 'តើ KCMS មានតម្លៃប៉ុន្មាន?',
        answer: 'KCMS កំពុងទទួលអង្គការសាកល្បង។ តម្លៃនាពេលអនាគតអាចអាស្រ័យលើចំនួន Facebook Page ដែលបានភ្ជាប់។ សូមទាក់ទងយើងដើម្បីពិភាក្សាអំពីការចូលប្រើសាកល្បង។',
      },
    ],
    footerNavLabel: 'ការរុករកផ្នែកខាងក្រោម',
    footerTagline: 'ការគ្រប់គ្រងមតិយោបល់ Facebook ជាភាសាខ្មែរ ដោយមនុស្សគ្រប់គ្រងគ្រប់សកម្មភាព។',
    footerProduct: 'ផលិតផល',
    footerAccess: 'ការចូលប្រើ',
    footerInformation: 'ព័ត៌មាន',
    footerContact: 'ទំនាក់ទំនង',
    footerPrivacy: 'ឯកជនភាព',
    footerStatusLabel: 'ស្ថានភាព Prototype',
    footerStatus: 'ការផ្គូផ្គងលំនាំមានកំណែ · ត្រូវការការពិនិត្យដោយមនុស្ស',
    footerRights: '© 2026 KCMS',
  },
} as const

export type Locale = keyof typeof copy
