/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Comments */
        get: operations["listComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{comment_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Action
         * @description Records a moderation Action. Actions are append-only and reversible,
         *     and never become training labels.
         */
        post: operations["recordAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Database-aware service health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionRequest */
        ActionRequest: {
            /**
             * Actor
             * @default demo-client
             */
            actor: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "LEAVE" | "HIDE" | "UNHIDE";
        };
        /**
         * DatabaseStatus
         * @enum {string}
         */
        DatabaseStatus: "REACHABLE" | "UNREACHABLE";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Contract Version
             * @example 1.0.0
             */
            contract_version: string;
            database: components["schemas"]["DatabaseStatus"];
            /**
             * Service
             * @example kcms-backend
             */
            service: string;
            status: components["schemas"]["ServiceStatus"];
        };
        /** HistoryEntry */
        HistoryEntry: {
            /** Actor */
            actor: string;
            /** Kind */
            kind: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /**
         * ServiceStatus
         * @enum {string}
         */
        ServiceStatus: "READY" | "DEGRADED";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkList */
        WorkList: {
            /** Items */
            items: components["schemas"]["WorkListItem"][];
            /** Total */
            total: number;
        };
        /** WorkListItem */
        WorkListItem: {
            /** Abstain */
            abstain: boolean | null;
            /** Author Ref */
            author_ref: string;
            /** Comment Id */
            comment_id: string;
            /** Latest Action */
            latest_action: string | null;
            /** Latest Action At */
            latest_action_at: string | null;
            /** Latest Actor */
            latest_actor: string | null;
            /** Model Version */
            model_version: string | null;
            /**
             * Posted At
             * Format: date-time
             */
            posted_at: string;
            /** Rationale */
            rationale: string | null;
            /** Severity */
            severity: string | null;
            /** Severity Confidence */
            severity_confidence: number | null;
            /** Surfaced Reason */
            surfaced_reason: string | null;
            /** Target */
            target: string | null;
            /** Target Confidence */
            target_confidence: number | null;
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listComments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkList"];
                };
            };
        };
    };
    recordAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
