/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/pilot-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pilot Requests */
        get: operations["listPilotRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pilot-requests/{request_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Pilot Request */
        post: operations["decidePilotRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["listAuthProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign In */
        post: operations["signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Out */
        post: operations["signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign In With Telegram */
        post: operations["signInWithTelegram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Comments */
        get: operations["listComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Sample Comments
         * @description Clear the seeded sample comments from this workspace.
         *
         *     Only the samples are removed: the delete is scoped by the sample Page id,
         *     so comments imported from a connected Facebook Page are never touched.
         *     Emptying a shared workspace affects everyone in it, so it is an owner
         *     action rather than something any member can do.
         */
        delete: operations["removeSampleComments"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["getWorkspaceSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{comment_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Action
         * @description Records a moderation Action. Actions are append-only and reversible,
         *     and never become training labels.
         *
         *     When the comment came from a connected Facebook Page, HIDE and UNHIDE are
         *     applied on Facebook as well. The Action row and the Facebook state are
         *     written together: if Facebook refuses, the row is rolled back, because an
         *     Action records what actually happened to the comment.
         */
        post: operations["recordAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{comment_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Correction
         * @description Records what a human asserts the labels should be.
         *
         *     A Correction is not an Action. Submitting one does not hide, unhide or
         *     otherwise change what happens to the comment.
         */
        post: operations["recordCorrection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facebook/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["listFacebookConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facebook/connections/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect Manually */
        post: operations["connectFacebookPageManually"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facebook/connections/{page_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect */
        delete: operations["disconnectFacebookPage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facebook/connections/{page_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Comments
         * @description Pull comments from the connected Page into this workspace.
         *
         *     Re-syncing is safe: the provider's comment id is the primary key, so an
         *     already-imported comment keeps its verdict, actions and corrections.
         */
        post: operations["syncFacebookComments"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facebook/oauth/sessions/{state}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Page Choices */
        get: operations["listFacebookPageChoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facebook/oauth/sessions/{state}/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Page */
        post: operations["selectFacebookPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facebook/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Authorization */
        post: operations["startFacebookAuthorization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Database-aware service health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pilot-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Pilot Request */
        post: operations["createPilotRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename Self
         * @description Anyone may change their own display name. It affects how future actions
         *     are attributed; past actions keep the name used at the time.
         */
        patch: operations["renameSelf"];
        trace?: never;
    };
    "/api/v1/settings/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename Workspace */
        patch: operations["renameWorkspace"];
        trace?: never;
    };
    "/api/v1/setup-invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Setup Invitation */
        get: operations["previewSetupInvitation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup-invitations/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Setup Invitation */
        post: operations["acceptSetupInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team */
        get: operations["getTeam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Invitation */
        post: operations["createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/invitations/{token_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invitation */
        delete: operations["revokeInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/invitations/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invitation */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/invitations/{token}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Invitation
         * @description Public: someone following a link needs to know what they are joining
         *     before signing in. Reveals the workspace name and role, nothing else.
         */
        get: operations["previewInvitation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionRequest */
        ActionRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "LEAVE" | "HIDE" | "UNHIDE";
        };
        /** AdminPilotRequest */
        AdminPilotRequest: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
            /** Decision Reason */
            decision_reason: string | null;
            /** Delivery Status */
            delivery_status?: string | null;
            /** Email */
            email: string;
            /** Facebook Page */
            facebook_page: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Note */
            note: string | null;
            /** Organization */
            organization: string;
            /** Status */
            status: string;
        };
        /** AuthUser */
        AuthUser: {
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            /**
             * Is Platform Admin
             * @default false
             */
            is_platform_admin: boolean;
        };
        /** CorrectionRequest */
        CorrectionRequest: {
            /** Note */
            note?: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "SAFE" | "OFFENSIVE" | "HARMFUL";
            /**
             * Target
             * @enum {string}
             */
            target: "PERSON" | "INSTITUTION" | "NEITHER";
        };
        /** CorrectionResponse */
        CorrectionResponse: {
            /** Actor */
            actor: string;
            /** Disagrees With Model */
            disagrees_with_model: string;
            /** Note */
            note: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Severity */
            severity: string;
            /** Target */
            target: string;
        };
        /** CreateInvitation */
        CreateInvitation: {
            /**
             * Role
             * @default member
             * @enum {string}
             */
            role: "owner" | "member";
        };
        /** CreatedInvitation */
        CreatedInvitation: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Role */
            role: string;
            /** Token */
            token: string;
        };
        /**
         * DatabaseStatus
         * @enum {string}
         */
        DatabaseStatus: "REACHABLE" | "UNREACHABLE";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Contract Version
             * @example 1.0.0
             */
            contract_version: string;
            database: components["schemas"]["DatabaseStatus"];
            /**
             * Service
             * @example kcms-backend
             */
            service: string;
            status: components["schemas"]["ServiceStatus"];
        };
        /** HistoryEntry */
        HistoryEntry: {
            /** Actor */
            actor: string;
            /** Kind */
            kind: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** Invitation */
        Invitation: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Role */
            role: string;
            /** Token Hash */
            token_hash: string;
        };
        /** InvitationPreview */
        InvitationPreview: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Role */
            role: string;
            /** Workspace Name */
            workspace_name: string;
        };
        /** JoinedWorkspace */
        JoinedWorkspace: {
            /** Workspace Id */
            workspace_id: string;
            /** Workspace Name */
            workspace_name: string;
        };
        /** ManualPageConnection */
        ManualPageConnection: {
            /** Page Access Token */
            page_access_token: string;
        };
        /** Member */
        Member: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string | null;
            /** Role */
            role: string;
            /** User Id */
            user_id: string;
        };
        /** OAuthStart */
        OAuthStart: {
            /** Authorization Url */
            authorization_url: string;
        };
        /** PageChoice */
        PageChoice: {
            /** Can Moderate */
            can_moderate: boolean;
            /** Page Id */
            page_id: string;
            /** Page Name */
            page_name: string;
            /** Tasks */
            tasks: string[];
        };
        /** PageChoices */
        PageChoices: {
            /** Pages */
            pages: components["schemas"]["PageChoice"][];
        };
        /** PageConnection */
        PageConnection: {
            /** Can Moderate */
            can_moderate: boolean;
            /**
             * Connected At
             * Format: date-time
             */
            connected_at: string;
            /** Last Synced At */
            last_synced_at: string | null;
            /**
             * Method
             * @enum {string}
             */
            method: "FACEBOOK_LOGIN" | "MANUAL_TOKEN";
            /** Page Id */
            page_id: string;
            /** Page Name */
            page_name: string;
            /**
             * State
             * @default CONNECTED
             * @constant
             */
            state: "CONNECTED";
            /** Tasks */
            tasks: string[];
        };
        /** PageConnections */
        PageConnections: {
            /** Connections */
            connections: components["schemas"]["PageConnection"][];
            /** Page Limit */
            page_limit: number;
            /**
             * Plan
             * @enum {string}
             */
            plan: "STARTER" | "GROWTH";
        };
        /** PilotDecision */
        PilotDecision: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "APPROVED" | "DECLINED";
            /** Reason */
            reason?: string | null;
        };
        /** PilotDecisionResult */
        PilotDecisionResult: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
            /** Decision Reason */
            decision_reason: string | null;
            /** Delivery Status */
            delivery_status: string;
            /** Email */
            email: string;
            /** Facebook Page */
            facebook_page: string;
            /** Id */
            id: string;
            /** Invitation Url */
            invitation_url: string | null;
            /** Name */
            name: string;
            /** Note */
            note: string | null;
            /** Organization */
            organization: string;
            /** Status */
            status: string;
        };
        /** PilotRequestCreate */
        PilotRequestCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Facebook Page */
            facebook_page: string;
            /** Name */
            name: string;
            /** Note */
            note?: string | null;
            /** Organization */
            organization: string;
        };
        /** PilotRequestReceipt */
        PilotRequestReceipt: {
            /** Id */
            id: string;
            /** Message */
            message: string;
            /** Status */
            status: string;
        };
        /** Providers */
        Providers: {
            /** Email */
            email: boolean;
            /** Telegram */
            telegram: boolean;
            /** Telegram Bot Username */
            telegram_bot_username: string | null;
        };
        /** ReasonCount */
        ReasonCount: {
            /** Count */
            count: number;
            /** Surfaced Reason */
            surfaced_reason: string;
        };
        /** RenameSelf */
        RenameSelf: {
            /** Display Name */
            display_name: string;
        };
        /** RenameWorkspace */
        RenameWorkspace: {
            /** Name */
            name: string;
        };
        /** SampleRemoval */
        SampleRemoval: {
            /** Removed */
            removed: number;
        };
        /** SelectPage */
        SelectPage: {
            /** Page Id */
            page_id: string;
        };
        /**
         * ServiceStatus
         * @enum {string}
         */
        ServiceStatus: "READY" | "DEGRADED";
        /** Session */
        Session: {
            /** Token */
            token: string;
            user: components["schemas"]["AuthUser"];
        };
        /** SetupInvitationAccept */
        SetupInvitationAccept: {
            /** Display Name */
            display_name: string;
            /** Password */
            password: string;
        };
        /** SetupInvitationPreview */
        SetupInvitationPreview: {
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Organization */
            organization: string;
        };
        /** SignInRequest */
        SignInRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * Summary
         * @description Counts computed across the whole workspace, not from one page.
         */
        Summary: {
            /** Hidden */
            hidden: number;
            /** Left Visible */
            left_visible: number;
            /** Need Review */
            need_review: number;
            /** Pending */
            pending: number;
            /** Processed */
            processed: number;
            /** Reasons */
            reasons: components["schemas"]["ReasonCount"][];
            /** Reviewed */
            reviewed: number;
            /** Unhidden */
            unhidden: number;
        };
        /** SyncResult */
        SyncResult: {
            /** Fetched */
            fetched: number;
            /** Imported */
            imported: number;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Page Id */
            page_id: string;
            /** Page Name */
            page_name: string;
        };
        /** Team */
        Team: {
            /** Invitations */
            invitations: components["schemas"]["Invitation"][];
            /** Members */
            members: components["schemas"]["Member"][];
            /** Workspace Id */
            workspace_id: string;
            /** Workspace Name */
            workspace_name: string;
            /** Your Role */
            your_role: string;
        };
        /** TelegramRequest */
        TelegramRequest: {
            /** Payload */
            payload: {
                [key: string]: string;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkList */
        WorkList: {
            /** Items */
            items: components["schemas"]["WorkListItem"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** WorkListItem */
        WorkListItem: {
            /** Abstain */
            abstain: boolean | null;
            /** Author Ref */
            author_ref: string;
            /** Comment Id */
            comment_id: string;
            /** Corrected At */
            corrected_at: string | null;
            /** Corrected By */
            corrected_by: string | null;
            /** Corrected Severity */
            corrected_severity: string | null;
            /** Corrected Target */
            corrected_target: string | null;
            /** Is Reply */
            is_reply: boolean;
            /** Latest Action */
            latest_action: string | null;
            /** Latest Action At */
            latest_action_at: string | null;
            /** Latest Action On Facebook */
            latest_action_on_facebook: boolean | null;
            /** Latest Actor */
            latest_actor: string | null;
            /** Model Version */
            model_version: string | null;
            /** Page Id */
            page_id: string;
            /** Parent Text */
            parent_text: string | null;
            /** Post Kind */
            post_kind: string;
            /** Post Permalink */
            post_permalink: string | null;
            /** Post Text */
            post_text: string | null;
            /**
             * Posted At
             * Format: date-time
             */
            posted_at: string;
            /** Rationale */
            rationale: string | null;
            /** Severity */
            severity: string | null;
            /** Severity Confidence */
            severity_confidence: number | null;
            /** Surfaced Reason */
            surfaced_reason: string | null;
            /** Target */
            target: string | null;
            /** Target Confidence */
            target_confidence: number | null;
            /** Text */
            text: string;
        };
        /** WorkspaceSettings */
        WorkspaceSettings: {
            /** Display Name */
            display_name: string;
            /** Is Sandbox */
            is_sandbox: boolean;
            /** Sample Comments */
            sample_comments: number;
            /** Workspace Id */
            workspace_id: string;
            /** Workspace Name */
            workspace_name: string;
            /** Your Role */
            your_role: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPilotRequests: {
        parameters: {
            query?: {
                status?: ("PENDING" | "APPROVED" | "DECLINED") | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPilotRequest"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decidePilotRequest: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PilotDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PilotDecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listAuthProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Providers"];
                };
            };
        };
    };
    signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signInWithTelegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listComments: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                query?: string | null;
                severity?: ("SAFE" | "OFFENSIVE" | "HARMFUL") | null;
                target?: ("PERSON" | "INSTITUTION" | "NEITHER") | null;
                surfaced_reason?: ("triage" | "institution_sample" | "novel_language" | "uncertainty" | "cleared") | null;
                review_status?: ("PENDING" | "ACTIONED") | null;
                sort?: "PRIORITY" | "NEWEST" | "OLDEST";
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    removeSampleComments: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleRemoval"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getWorkspaceSummary: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recordAction: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                comment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recordCorrection: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                comment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listFacebookConnections: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageConnections"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connectFacebookPageManually: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualPageConnection"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageConnection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnectFacebookPage: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    syncFacebookComments: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listFacebookPageChoices: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                state: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageChoices"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    selectFacebookPage: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                state: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectPage"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageConnection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    startFacebookAuthorization: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    createPilotRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PilotRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PilotRequestReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renameSelf: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameSelf"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renameWorkspace: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameWorkspace"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    previewSetupInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupInvitationPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acceptSetupInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupInvitationAccept"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createInvitation: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitation"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedInvitation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revokeInvitation: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                token_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinedWorkspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    previewInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
